class_name DialogueData
extends RefCounted

# 대화 노드 구조 예시:
# {
#     "id": String,
#     "speaker": String,
#     "text": String,
#     "narration": String,          # 기본 "". 괄호로 된 행동 묘사(지문) — 이탤릭으로 별도 표시됨.
#                                    # text 없이 narration만 있는 노드(순수 지문)도 가능.
#     "is_decisive": bool,          # 기본 false. UI 강조(금색 테두리) 용도 — 이 노드가 결정적 질문임을 표시
#     "options": [
#         {
#             "label": String,
#             "next_id": String,
#             "flag_to_set": String, # 이 옵션을 선택하면 설정할 flag, 없으면 ""(생략 가능)
#             "flag_value": bool,    # flag_to_set이 있을 때 설정할 값
#             "show_if_flag": String, # 이 flag가 true일 때만 옵션을 보여줌, 없으면 ""(항상 표시, 생략 가능)
#             "show_if_seen": String, # 이 node_id를 이미 본 적 있을 때만 옵션을 보여줌 (생략 가능)
#             "show_if_not_seen": String, # 이 node_id를 아직 안 봤을 때만 옵션을 보여줌 — show_if_seen과
#                                    # 짝지으면 "본 적 있으면 A 대신 B" 식으로 옵션을 서로 대체할 수 있음 (생략 가능)
#             "required_affinity": { "npc_id": String, "min": int },
#                                    # 지정 시, 해당 NPC 호감도가 min 이상일 때만 선택 가능. 미만이면
#                                    # 옵션은 보이되 빨간색으로 표시되고 클릭해도 안내만 뜨고 진행되지 않음 (생략 가능)
#             "affinity_change": { "npc_id": String, "amount": int },
#                                    # 지정 시, 이 옵션을 선택하면 해당 NPC 호감도를 amount만큼 증감 (생략 가능)
#             "next_id_by_affinity": { "npc_id": String, "thresholds": [int, ...], "next_ids": [String, ...] },
#                                    # 지정 시, next_id 대신 현재 호감도로 다음 노드를 고른다
#                                    # (next_ids.size() == thresholds.size() + 1). 낮은 threshold부터 비교해
#                                    # 처음 "호감도 < threshold"인 구간의 next_id를 쓰고, 전부보다 크면 마지막
#                                    # next_id(최상위 구간)를 쓴다. 예: thresholds=[40,70], next_ids=[A,B,C]
#                                    # -> <40: A, 40~69: B, 70+: C. 고정 4단계(cold/neutral/warm/trusted)
#                                    # 명칭에 안 맞는 커스텀 구간이 필요할 때 씀 (생략 가능, 있으면 next_id보다 우선)
#         },
#     ],
# }
#
# 옵션의 next_id가 이미 방문한 노드(GameState.seen_dialogue_nodes)면, DialogueBox가 그 옵션을
# 회색으로 표시하고 목록 맨 아래로 정렬한다 (다시 들을 수 있지만 시각적으로 구분됨) — 데이터에 별도 표기 불필요.
#
# 노드에 "affinity_change_on_show": { "npc_id": String, "amount": int }를 넣으면, 옵션 선택과 무관하게
# 그 노드가 화면에 표시되는 순간 호감도가 바뀐다 (선택지 없이 이어지는 서술형 노드에 쓰는 용도 —
# 옵션 선택 시 효과를 주고 싶으면 옵션의 "affinity_change"를 대신 사용).
#
# 노드에 "text_by_affinity_tier": { "npc_id": String, "cold": String, "neutral": String, "warm": String,
# "trusted": String }를 넣으면, 해당 NPC의 현재 호감도 구간(GameState.get_affinity_tier)에 맞는 문구를
# 보여준다 (구간별 문구가 없으면 "text"로 폴백). 이진 분기인 text_if_flag와 달리 4단계 분기용.
#
# 결정적 선택은 "노드를 보여주는 순간"이 아니라 "옵션을 고르는 순간" flag가 설정된다.
# 즉 결정적 노드는 보통 options에 2개(각각 다른 flag_value)를 넣어, 그중 하나를
# 고르는 행위 자체가 곧 그 선택이 되도록 구성한다.
#
# 노드에 "options"가 없거나 비어 있을 때:
# - 노드 최상위에 "next_id": String이 있으면(분기 없는 단순 다음 대사) "[계속]" 버튼을 자동으로 보여준다.
# - 없으면(진짜 종료 대사) 기본 "닫기" 버튼을 보여준다.
# 매 노드마다 종료/계속용 옵션을 직접 넣을 필요는 없다.
#
# 노드에 "text_if_flag": String을 넣으면, 그 flag가 true일 때 "text"를,
# false일 때 "text_false"를 보여준다 (조건부 대사용, 둘 다 없으면 생략 가능).

# 테스트용 예시 대화 트리 (실제 대사는 아직 없음, 구조 검증 목적)
const TEST_DIALOGUE: Array = [
	{
		"id": "start",
		"speaker": "Test NPC",
		"text": "[테스트 대사 1] 분기 선택지 예시",
		"is_decisive": false,
		"options": [
			{"label": "[테스트 선택 A]", "next_id": "branch_a"},
			{"label": "[테스트 선택 B]", "next_id": "branch_b"},
		],
	},
	{
		"id": "branch_a",
		"speaker": "Test NPC",
		"text": "[테스트 대사 2A] 선택 A로 이어지는 대사",
		"is_decisive": false,
		"options": [
			{"label": "[계속]", "next_id": "decisive_example"},
		],
	},
	{
		"id": "branch_b",
		"speaker": "Test NPC",
		"text": "[테스트 대사 2B] 선택 B로 이어지는 대사",
		"is_decisive": false,
		"options": [
			{"label": "[계속]", "next_id": "decisive_example"},
		],
	},
	{
		"id": "decisive_example",
		"speaker": "Test NPC",
		"text": "[테스트 결정적 대사] 아래 두 선택지 중 하나를 고르면 그 자체가 flag를 정함",
		"is_decisive": true,
		"options": [
			{"label": "[결정적 선택 A]", "next_id": "", "flag_to_set": "test_flag_example", "flag_value": true},
			{"label": "[결정적 선택 B]", "next_id": "", "flag_to_set": "test_flag_example", "flag_value": false},
		],
	},
]

# 엘라라(장로) 대화 트리
const ELARA_DIALOGUE: Array = [
	{
		"id": "elara_greeting",
		"speaker": "엘라라",
		"text": "오, 자네로군. 우물 일 때문에 왔겠지.",
		"text_by_affinity_tier": {
			"npc_id": "elara",
			"cold": "...무슨 일이지.",
			"neutral": "오, 자네로군. 우물 일 때문에 왔겠지.",
			"warm": "왔는가. 자네를 보면 마음이 놓이는군.",
			"trusted": "자네가 와줘서 다행이야. 요즘 자네 얼굴을 보면 든든해.",
		},
		"is_decisive": false,
		"options": [
			{"label": "[우물에 대해 묻는다]", "next_id": "elara_well"},
			{"label": "[마을에 대해 묻는다]", "next_id": "elara_village"},
			{"label": "[그냥 안부를 묻는다]", "next_id": "elara_smalltalk"},
			{"label": "[의뢰? 뭐 일거리 있나요?]", "next_id": "elara_bounty_intro"},
			{"label": "[다른 사람들에 대해 묻는다]", "next_id": "elara_gossip", "show_if_flag": "met_rohan"},
			{"label": "[다녀왔다고 말한다]", "next_id": "elara_ending_check", "show_if_flag": "guardian_event_done"},
			{
				"label": "[궁금한 게 있어요, 장로님]",
				"next_id": "elara_secret_intro",
				"required_affinity": {"npc_id": "elara", "min": 60},
				"show_if_not_seen": "elara_secret_end",
			},
			{
				"label": "[그 기록에 대해서 더 생각해봤나]",
				"next_id": "elara_secret_followup",
				"show_if_seen": "elara_secret_end",
			},
			{
				"label": "[그 기록에 대해 좀 더 자세히 들려주실 수 있어요?]",
				"next_id": "elara_secret_stage2_1",
				"show_if_seen": "elara_secret_end",
			},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "elara", "amount": 9, "next_id_success": "elara_gift_thanks", "next_id_fail": "elara_gift_none"},
			},
		],
	},
	{
		"id": "elara_bounty_intro",
		"speaker": "엘라라",
		"text": "마침 잘 왔군. 마을 사람들이 붙여둔 의뢰가 몇 있네. 손이 비었으면 한번 보게나.",
		"is_decisive": false,
		"options": [
			{"label": "[의뢰판을 살펴본다]", "open_bounty_board": true},
			{"label": "[다음에 볼게요]", "next_id": ""},
		],
	},
	{
		"id": "elara_gift_thanks",
		"speaker": "엘라라",
		"text": "이런 걸... 나한테? 허허, 고맙구나. 늙은이 마음이 다 따뜻해지는군.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_gift_none",
		"speaker": "엘라라",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_well",
		"speaker": "엘라라",
		"text": "그래, 그 얘기가 궁금하겠지. 요 며칠 마을이 영 어수선하지 않은가.",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[무슨 일이에요?]", "next_id": "elara_well_incident"},
		],
	},
	{
		"id": "elara_well_incident",
		"speaker": "엘라라",
		"text": "사흘 전 밤 얘기일세... 정확히는... 아마 자정이 막 지났을 무렵이었지. 마을 전체가 콰광! 하고 흔들린 게야! 자다가 놀라서 벌떡 일어난 사람이 한둘이 아니었다니까. 나도 그랬고.",
		"is_decisive": false,
		"next_id": "elara_well_light",
	},
	{
		"id": "elara_well_light",
		"speaker": "엘라라",
		"text": "그리고 그 직후에, 저 동굴 쪽 하늘이 잠깐 이상한 빛으로 물들었다더군. 나는 못 봤네만, 그날 늦게까지 안 자고 있던 사람 몇이 봤다고 하더군. 파르스름한, 이 세상 것 같지 않은 빛이었다고 말이야.",
		"is_decisive": false,
		"next_id": "elara_well_dry",
	},
	{
		"id": "elara_well_dry",
		"speaker": "엘라라",
		"text": "그리고 다음 날 아침, 글쎄 우물지기가 두레박을 내렸는데 바닥까지 텅 비어 있지 뭔가. 하룻밤 사이에 그리 된 게야. 이 마을이 생긴 이래로 우물이 마른 적은 단 한 번도 없었네.",
		"is_decisive": false,
		"options": [
			{"label": "[그냥 우연 아닐까요?]", "next_id": "elara_well_react_a"},
			{"label": "[심상치 않네요]", "next_id": "elara_well_react_b"},
		],
	},
	{
		"id": "elara_well_react_a",
		"speaker": "엘라라",
		"text": "나도 처음엔 그리 생각했지. 가뭄이야 흔한 일이니까. 근데 하룻밤 사이에, 그것도 그런 빛과 흔들림과 함께라면... 우연이라기엔 너무 겹치는군.",
		"is_decisive": false,
		"next_id": "elara_well_altar",
	},
	{
		"id": "elara_well_react_b",
		"speaker": "엘라라",
		"text": "자네도 그리 느꼈나. 나도 마찬가지야. 오래 살다 보면 이상한 일 몇 번은 겪게 마련인데, 이번 건 좀 다르더군.",
		"is_decisive": false,
		"next_id": "elara_well_altar",
	},
	{
		"id": "elara_well_altar",
		"speaker": "엘라라",
		"text": "사실 이 동굴에 대해서는, 우리 마을에 아주 오래전부터 내려오는 이야기가 하나 있어. 자네도 저 돌 제단 같은 거 본 적 있나?",
		"is_decisive": false,
		"options": [
			{"label": "[아니요, 못 봤어요]", "next_id": "elara_well_legend"},
			{"label": "[본 것 같아요]", "next_id": "elara_well_legend"},
		],
	},
	{
		"id": "elara_well_legend",
		"speaker": "엘라라",
		"text": "옛날에는 마을 사람들이 거기에 물과 꽃을 놓고 갔다더군. \"물지기께 드리는 인사\"라고 불렀다지. 나 어릴 때만 해도 할머니 손 잡고 몇 번 가본 기억이 있어. 지금은 다들 안 하지만.",
		"is_decisive": false,
		"next_id": "elara_well_legend2",
	},
	{
		"id": "elara_well_legend2",
		"speaker": "엘라라",
		"text": "그 물지기라는 게 뭐냐 하면, 이 땅 밑을 흐르는 물줄기를 지켜주는 존재라고 했어. 동굴 깊은 곳에 잠들어 있으면서, 우리가 쓰는 물이 마르지 않게 돌봐준다고. 다들 그냥 옛날이야기라고 여겼지, 나도 마찬가지였고. 근데 이번 일을 보니... 영 아니라고는 못하겠군.",
		"is_decisive": false,
		"options": [
			{"label": "[그 존재가 우물을 마르게 한 걸까요?]", "next_id": "elara_well_puzzle"},
		],
	},
	{
		"id": "elara_well_puzzle",
		"speaker": "엘라라",
		"text": "모르지. 근데 이상하지 않나. 지켜주는 존재라면서 왜 갑자기 물을 막겠나. 앞뒤가 안 맞아. 하지만 뭔가 있는 건 분명해 보이니, 확인은 해봐야 하지 않겠나.",
		"is_decisive": false,
		"next_id": "elara_well_send_rohan",
	},
	{
		"id": "elara_well_send_rohan",
		"speaker": "엘라라",
		"text": "혼자 가는 건 말리고 싶네만... 자네라면 괜찮을 것 같기도 하고. 그래도 준비는 좀 하고 가게. 우선 로한을 찾아가보게. 그 사람이 숲 쪽에 살다시피 하는데, 마침 그날 밤 근처에 있었다고 오늘 아침에 여기 들러서 그러더군. 얼굴이 하얗게 질려서 말이야.",
		"is_decisive": false,
		"next_id": "elara_well_send_mia",
	},
	{
		"id": "elara_well_send_mia",
		"speaker": "엘라라",
		"text": "아, 그리고... 미아 얘기도 들었나 모르겠군. 그 어머니가 어제 나한테 와서 걱정을 늘어놓더군. 그 아이도 그날 밤 밖에 있었다지 뭔가. 원래도 잠을 잘 못 자는 아이라 가끔 밤에 나가 돌아다니는 걸 다들 알고는 있었는데, 그날은 새벽에 울면서 뛰어들어와선 며칠째 말을 거의 안 하고 있다는군. 조심스럽게 다가가보게, 지금은 어른들도 무서운 모양이니.",
		"is_decisive": false,
		"next_id": "elara_well_send_yusuf",
	},
	{
		"id": "elara_well_send_yusuf",
		"speaker": "엘라라",
		"text": "그리고 저잣거리에 있는 유서프도 한번 만나보게. 어제 사람들한테 이 얘기를 하는 걸 얼핏 들었는데, 뭔가 아는 눈치더군. 그 친구야 여기저기 떠돌아다니는 장사꾼이니, 혹시 다른 마을에서도 비슷한 일이 있었는지 알지도 모르지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_ending_check",
		"speaker": "엘라라",
		"narration": "(마을 광장, 밤)",
		"text": "(플레이어를 보자마자 안도하며) 무사히 왔군! ...우물은, 어떻게 됐나?",
		"is_decisive": false,
		"options": [
			{"label": "[해결했어요. 근데...]", "next_id": "elara_ending_fight_1", "show_if_flag_false": "resolved_guardian_peacefully"},
			{"label": "[해결했어요. 근데...]", "next_id": "elara_ending_peace_1", "show_if_flag": "resolved_guardian_peacefully"},
		],
	},
	{
		"id": "elara_ending_fight_1",
		"speaker": "엘라라",
		"narration": "(안도의 한숨, 그러나 표정이 완전히 밝지만은 않다)",
		"text": "처치했다고... 다행이군. 정말 다행이야.",
		"is_decisive": false,
		"options": [
			{"label": "[근데 마지막에... 사람처럼 말을 했어요. \"미안하다\"고.]", "next_id": "elara_ending_fight_2"},
		],
	},
	{
		"id": "elara_ending_fight_2",
		"speaker": "엘라라",
		"narration": "(표정이 굳는다)",
		"text": "...그게, 무슨 말인가.",
		"is_decisive": false,
		"options": [
			{"label": "[모르겠어요. 그냥 그렇게 들렸어요.]", "next_id": "elara_ending_fight_3"},
		],
	},
	{
		"id": "elara_ending_fight_3",
		"speaker": "엘라라",
		"narration": "(한참 침묵)",
		"text": "...내가 아는 전설은 거기까지가 다일세. 그 이상은 나도 모르는 일이야. 다만... 자네가 들은 게 헛것이 아니라면, 이 이야기가 우리가 아는 것보다 훨씬 깊을지도 모르겠군.",
		"is_decisive": false,
		"options": [
			{"label": "[근데 이상한 게, 물이 원래 우물에서 나오던 양이 아니에요. 훨씬 많아요. 마치... 처음부터 이래야 했던 것처럼요.]", "next_id": "elara_ending_water_1"},
		],
	},
	{
		"id": "elara_ending_peace_1",
		"speaker": "엘라라",
		"text": "해결... 이라니, 어떻게 한 겐가?",
		"is_decisive": false,
		"options": [
			{"label": "[싸우지 않고 이야기했어요. 근데... 사라지기 전에, 사람처럼 말을 하고서 사라졌어요.]", "next_id": "elara_ending_peace_2"},
		],
	},
	{
		"id": "elara_ending_peace_2",
		"speaker": "엘라라",
		"narration": "(놀라며)",
		"text": "사람처럼... 말을 했다고? 살아있는 게 아니고?",
		"is_decisive": false,
		"options": [
			{"label": "[네. \"얼마나 됐을까, 묶인 지\"라고 하더니 — 마지막엔 \"감시자들은 지하에 있다\"는 말을 하다 말고, 그대로 사라졌어요.]", "next_id": "elara_ending_peace_3"},
		],
	},
	{
		"id": "elara_ending_peace_3",
		"speaker": "엘라라",
		"narration": "(표정이 심각해진다)",
		"text": "...묶여 있었다... 그 말은, 그게 원래부터 저기 있던 게 아니라, 누군가 가둬놓은 거였단 소리 아닌가. 그것도, 사람을. ...게다가 \"감시자\"라니, 나는 처음 듣는 이름이군.",
		"is_decisive": false,
		"next_id": "elara_ending_peace_4",
	},
	{
		"id": "elara_ending_peace_4",
		"speaker": "엘라라",
		"narration": "(자신에게 말하듯, 그리고 플레이어를 본다)",
		"text": "대체 누가, 왜 사람을 가둬서... ...미안하네, 나도 이 이상은 아는 게 없어. 다만 그 말, 꼭 기억해두게 — \"감시자\"와 \"지하\". 예사롭게 들리지 않는군.",
		"is_decisive": false,
		"options": [
			{"label": "[근데 이상한 게, 물이 원래 우물에서 나오던 양이 아니에요. 훨씬 많아요. 마치... 처음부터 이래야 했던 것처럼요.]", "next_id": "elara_ending_water_1"},
		],
	},
	{
		"id": "elara_ending_water_1",
		"speaker": "엘라라",
		"narration": "(놀라며 우물 쪽을 돌아본다)",
		"text": "...그러고 보니, 오늘 저녁 우물 수위가 심상치 않게 높아졌다고 다들 그러더군. 이 정도였나. ...이건, 우리가 여태 알던 물의 양이 아니야.",
		"is_decisive": false,
		"next_id": "elara_ending_water_2",
	},
	{
		"id": "elara_ending_water_2",
		"speaker": "엘라라",
		"text": "이게 대체 뭘 뜻하는 건지 나도 모르겠네. 다만 이건 확실히 우리 마을만의 일이 아닌 것 같군. 유서프를 다시 찾아가보게. 그 친구, 아까보다 더 캐물어야 할 것 같아.",
		"is_decisive": false,
		"next_id": "elara_ending_trigger",
	},
	{
		"id": "elara_ending_trigger",
		"speaker": "엘라라",
		"text": "...그래. 이제 좀 지켜봐야겠군.",
		"set_flag_on_show": "part1_reported", # 엘라라 보고 완료 — 이후 objective가 2부(유서프→부두)로 넘어감
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_village",
		"speaker": "엘라라",
		"text": "작은 곳이지. 하지만 백 년 넘게 이 자리를 지켜왔어.",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[오래됐네요]", "next_id": "elara_village_old"},
			{"label": "[평화로워 보여요]", "next_id": "elara_village_peace"},
		],
	},
	{
		"id": "elara_village_old",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 1, "once": true},
		"speaker": "엘라라",
		"text": "그만큼 많은 걸 봐왔지. 좋은 일도, 나쁜 일도.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_village_peace",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 1, "once": true},
		"speaker": "엘라라",
		"text": "평화... 그래, 지금까진 그랬지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_smalltalk",
		"speaker": "엘라라",
		"text": "안부라... 다정하기도 하지. 몸은 성한가?",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[괜찮아요, 걱정 마세요]", "next_id": "elara_smalltalk_fine"},
			{"label": "[사실 좀 지쳤어요]", "next_id": "elara_smalltalk_tired"},
		],
	},
	{
		"id": "elara_smalltalk_fine",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 1, "once": true},
		"speaker": "엘라라",
		"text": "다행이군. 젊은이가 튼튼해야 마을도 든든하지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_smalltalk_tired",
		"affinity_change_on_show": {"npc_id": "elara", "amount": 1, "once": true},
		"speaker": "엘라라",
		"text": "쉬엄쉬엄하게. 우물이 급하다고 자네까지 쓰러지면 안 되지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_gossip",
		"speaker": "엘라라",
		"text": "[다른 사람들에 대해 물어본다]",
		"is_decisive": false,
		"options": [
			{"label": "[로한은 어떤 사람인가요?]", "next_id": "elara_about_rohan", "show_if_flag": "met_rohan"},
			{"label": "[유서프는 믿을 만한가요?]", "next_id": "elara_about_yusuf", "show_if_flag": "met_yusuf"},
			{"label": "[미아는 왜 저렇게 겁이 많나요?]", "next_id": "elara_about_mia", "show_if_flag": "met_mia"},
		],
	},
	{
		"id": "elara_about_rohan",
		"speaker": "엘라라",
		"text": "무뚝뚝하지만 마을을 아끼는 사람이야. 숲을 그만큼 잘 아는 이도 없지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_about_yusuf",
		"speaker": "엘라라",
		"text": "믿을 만하냐고... 글쎄. 유서프는 아는 게 너무 많아서 탈이지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_about_mia",
		"speaker": "엘라라",
		"text": "그 아이는... 얼마 전에 무서운 걸 봤다더군. 다그치지 말게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_secret_intro",
		"speaker": "엘라라",
		"text": "궁금한 거라... 흠, 자네라면 얘기해도 괜찮을 것 같군.",
		"is_decisive": false,
		"options": [
			{"label": "[무슨 이야기예요?]", "next_id": "elara_secret_1"},
			{"label": "[아니에요, 다음에 물어볼게요]", "next_id": ""},
		],
	},
	{
		"id": "elara_secret_1",
		"speaker": "엘라라",
		"text": "실은... 전대 장로님께 물려받은 게 하나 있어. 아주 오래된 기록이지.",
		"is_decisive": false,
		"next_id": "elara_secret_2",
	},
	{
		"id": "elara_secret_2",
		"speaker": "엘라라",
		"text": "이런 일이... 처음이 아니라는 기록이야. 아주 먼 옛날, 물줄기가 말랐던 적이 또 있었다더군.",
		"is_decisive": false,
		"options": [
			{"label": "[그때는 어떻게 됐나요?]", "next_id": "elara_secret_3"},
			{"label": "[왜 지금까지 숨기셨어요?]", "next_id": "elara_secret_alt"},
		],
	},
	{
		"id": "elara_secret_3",
		"speaker": "엘라라",
		"text": "기록엔... 그냥 '지나갔다'고만 적혀 있어. 어떻게 해결했는지는 안 적혀 있더군. 아니면... 적을 수 없었던 걸지도.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "elara", "amount": 3},
		"next_id": "elara_secret_end",
	},
	{
		"id": "elara_secret_alt",
		"speaker": "엘라라",
		"text": "자네도 알잖나, 사람들은 겁부터 먹어. 확실하지도 않은 걸로 마을을 불안하게 만들고 싶지 않았어.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "elara", "amount": 3},
		"next_id": "elara_secret_end",
	},
	{
		"id": "elara_secret_end",
		"speaker": "엘라라",
		"text": "...아무튼, 이런 얘긴 자네니까 하는 걸세. 다른 이들껜 아직은 비밀로 해주게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_secret_followup",
		"speaker": "엘라라",
		"text": "그 기록에 대해서 더 생각해봤나?",
		"is_decisive": false,
		"options": [
			{"label": "[아니요, 아직요]", "next_id": ""},
			{"label": "[혹시 다른 단서는 없었나요?]", "next_id": "elara_secret_followup2"},
		],
	},
	{
		"id": "elara_secret_followup2",
		"speaker": "엘라라",
		"text": "글쎄... 기록 마지막 장에 이상한 문양이 하나 그려져 있긴 했어. 무슨 뜻인지는 나도 몰라.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "elara_secret_stage2_1",
		"speaker": "엘라라",
		"narration": "(책장을 다시 펼치며)",
		"text": "사실... 다시 볼 때마다 이상한 부분이 있어. 여기, 이 대목 말일세.",
		"is_decisive": false,
		"next_id": "elara_secret_stage2_2",
	},
	{
		"id": "elara_secret_stage2_2",
		"speaker": "엘라라",
		"text": "\"물이 밤낮으로 넘쳐흘러, 마을 사람 누구도 목마름을 몰랐다.\" — 이렇게 적혀 있어. 처음엔 그냥 과장이겠거니 했지.",
		"is_decisive": false,
		"next_id": "elara_secret_stage2_3",
	},
	{
		"id": "elara_secret_stage2_3",
		"speaker": "엘라라",
		"text": "근데 요즘 자네랑 이런저런 얘길 나누다 보니... 이게 과장이 아니라 정말 그랬던 거라면? 지금 우리가 아는 물의 양이, 사실은 원래 있어야 할 양의 아주 일부에 불과한 거라면?",
		"is_decisive": false,
		"next_id": "elara_secret_stage2_4",
	},
	{
		"id": "elara_secret_stage2_4",
		"speaker": "엘라라",
		"narration": "(고개를 젓는다)",
		"text": "...나도 내가 무슨 말을 하는지 모르겠군. 그냥, 요즘 자꾸 이 기록이 마음에 걸려서 말이야.",
		"set_flag_on_show": "heard_ancient_abundance_hint",
		"is_decisive": false,
		"options": [],
	},
]

# 로한(사냥꾼) 대화 트리
const ROHAN_DIALOGUE: Array = [
	{
		"id": "rohan_locked_greeting",
		"speaker": "로한",
		"text": "...넌 누구지? 처음 보는 얼굴이군. 볼일 있으면 나중에.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_greeting",
		"speaker": "로한",
		"text": "거기 서. ...아, 마을에서 온 사람이군.",
		"text_by_affinity_tier": {
			"npc_id": "rohan",
			"cold": "...뭐야. 볼일 있으면 빨리 말해.",
			"neutral": "거기 서. ...아, 마을에서 온 사람이군.",
			"warm": "왔군. 요즘 자네 발소리는 구별이 되더라고.",
			"trusted": "왔나. 자네랑 얘기하는 게 요즘 낙이야, 이거.",
		},
		"is_decisive": false,
		"options": [
			{"label": "[동굴에 대해 묻는다]", "next_id": "rohan_cave"},
			{"label": "[숲에 대해 묻는다]", "next_id": "rohan_forest"},
			{"label": "[사냥은 잘 되냐고 묻는다]", "next_id": "rohan_smalltalk"},
			{"label": "[오크 처치를 돕겠다고 한다]", "next_id": "rohan_quest_accept", "start_quest": "forest_orcs", "show_if_quest_inactive": "forest_orcs"},
			{"label": "[오크는 어떻게 되어가요?]", "next_id": "rohan_quest_status", "show_if_quest_active": "forest_orcs"},
			{"label": "[다른 사람들에 대해 묻는다]", "next_id": "rohan_gossip", "show_if_flag": "met_elara"},
			{
				"label": "[뭔가 고민이 있어 보여요]",
				"next_id": "rohan_secret_intro",
				"required_affinity": {"npc_id": "rohan", "min": 60},
				"show_if_not_seen": "rohan_secret_end",
			},
			{
				"label": "[오크 얘기, 또 생각났나 보군]",
				"next_id": "rohan_secret_followup",
				"show_if_seen": "rohan_secret_end",
			},
			{
				"label": "[예전엔 숲이 어땠어요?]",
				"next_id": "rohan_secret_stage2_1",
				"show_if_seen": "rohan_secret_end",
			},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "rohan", "amount": 9, "next_id_success": "rohan_gift_thanks", "next_id_fail": "rohan_gift_none"},
			},
		],
	},
	{
		"id": "rohan_gift_thanks",
		"speaker": "로한",
		"text": "...나한테 선물을? 흠. ...고맙군. 이런 거, 오랜만이라 좀 어색하네.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_gift_none",
		"speaker": "로한",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_quest_accept",
		"speaker": "로한",
		"text": "고맙군. 숲에 오크 세 마리가 설치고 있어. 놈들을 처치해주면 마을이 한결 안전해질 거야. 조심하고.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_quest_status",
		"speaker": "로한",
		"text_if_flag": "forest_quest_complete",
		"text": "오크를 전부 처리했다고? ...대단하군. 정말 고생 많았어.",
		"text_false": "아직 놈들이 숲에 남아있군. 무리하지 말고 조심해.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_cave",
		"speaker": "로한",
		"narration": "(한숨)",
		"text": "그날 밤 얘기 말이군. ...앉게, 얘기가 좀 기니까.",
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 2, "once": true},
		"is_decisive": false,
		"next_id": "rohan_cave_3",
	},
	{
		"id": "rohan_cave_3",
		"speaker": "로한",
		"text": "요 몇 주째 여우고 살쾡이고 할 것 없이 마을 닭장 쪽으로 자꾸 내려오더군. 원래 이 계절엔 숲에 먹이가 충분해서 그럴 일이 없는데 말이야. 그래서 며칠 밤 순찰을 늘렸었네. 그날도 그래서 늦게까지 밖에 있었던 거고.",
		"is_decisive": false,
		"options": [
			{"label": "[그래서 뭘 보신 거예요?]", "next_id": "rohan_cave_4"},
		],
	},
	{
		"id": "rohan_cave_4",
		"speaker": "로한",
		"text": "자정 좀 넘어서였을 거야. 동굴 어귀 쪽에서 빛이 확 터지더니, 땅이 울렸어. 순간적으로 넘어질 뻔했다니까.",
		"is_decisive": false,
		"next_id": "rohan_cave_5",
	},
	{
		"id": "rohan_cave_5",
		"speaker": "로한",
		"text": "근데 진짜 소름 끼쳤던 건 그다음이야. 주변 짐승들이 죄다 미친 듯이 도망치기 시작했어. 새들이 한밤중에 떼로 날아오르고, 여우 한 마리는 내 앞을 그냥 지나쳐 가더군. 나를 보고도 신경도 안 쓸 정도로 말이야. 이 숲에서 십 년 넘게 사냥했는데, 그런 반응은 처음 봤어.",
		"is_decisive": false,
		"options": [
			{"label": "[혹시 옛날부터 전해지는 이야기 아세요?]", "next_id": "rohan_cave_6"},
		],
	},
	{
		"id": "rohan_cave_6",
		"speaker": "로한",
		"text": "물지기 얘기 말이지? 나도 어릴 때 들었지. 근데 진짜로 믿은 적은 없었어. 그냥 애들 겁주려고 하는 얘기인 줄 알았지 — \"밤에 동굴 근처 가면 물지기가 잡아간다\"는 식으로. 근데... 그날 그거 보고 나니 생각이 좀 달라지더군.",
		"is_decisive": false,
		"options": [
			{"label": "[혹시 도망 안 치셨어요?]", "next_id": "rohan_cave_7"},
		],
	},
	{
		"id": "rohan_cave_7",
		"speaker": "로한",
		"text": "쳤지, 나도 처음엔. 근데 몇 걸음 가다가 멈춰 섰어. 뭐랄까... 그 빛이, 무섭다기보단 이상하게 슬퍼 보였거든. 소리도 나더라고, 낮게 울리는 소리. 짐승 울음소리도 아니고, 그렇다고 사람 소리도 아니고. 지금 생각해도 뭐였는지 모르겠어.",
		"is_decisive": false,
		"next_id": "rohan_cave_end",
	},
	{
		"id": "rohan_cave_end",
		"speaker": "로한",
		"text": "아무튼 그 뒤로는 저 동굴 근처엔 얼씬도 안 해. 자네도 혼자 가지 말게. 유서프한테도 물어봐, 그 친구는 여기저기 떠돌아다니니까 다른 데서도 이런 일이 있었는지 알지도 몰라.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_forest",
		"speaker": "로한",
		"text": "조심해서 다녀. 요즘 숲이 심상치 않아.",
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[구체적으로 뭐가 이상한가요?]", "next_id": "rohan_forest_detail"},
			{"label": "[알겠어요]", "next_id": ""},
		],
	},
	{
		"id": "rohan_forest_detail",
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 1, "once": true},
		"speaker": "로한",
		"text": "나무들이... 말라가고 있어. 원래 이 계절엔 이러지 않는데.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_smalltalk",
		"speaker": "로한",
		"text": "사냥? ...요즘은 예전만 못해. 짐승들도 뭔가 눈치챈 건지 다들 숨어버렸어.",
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[짐승들이 왜 숨었을까요?]", "next_id": "rohan_smalltalk_animals"},
			{"label": "[그럼 뭘 드시고 사세요?]", "next_id": "rohan_smalltalk_food"},
		],
	},
	{
		"id": "rohan_smalltalk_animals",
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 1, "once": true},
		"speaker": "로한",
		"text": "글쎄. 짐승은 사람보다 먼저 위험을 아는 법이지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_smalltalk_food",
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 1, "once": true},
		"speaker": "로한",
		"text": "걱정 마. 굶어 죽을 정도는 아니니까.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_gossip",
		"speaker": "로한",
		"text": "[다른 사람들에 대해 물어본다]",
		"is_decisive": false,
		"options": [
			{"label": "[엘라라는 어떤 분인가요?]", "next_id": "rohan_about_elara", "show_if_flag": "met_elara"},
			{"label": "[유서프를 아세요?]", "next_id": "rohan_about_yusuf", "show_if_flag": "met_yusuf"},
		],
	},
	{
		"id": "rohan_about_elara",
		"speaker": "로한",
		"text": "장로님은... 이 마을에서 제일 오래 버틴 분이야. 함부로 대하지 마.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_about_yusuf",
		"speaker": "로한",
		"text": "그 상인? 나쁜 사람은 아닌데... 뭘 숨기고 있는 느낌이야.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_secret_intro",
		"speaker": "로한",
		"text": "...티가 나나. 하긴, 요즘 계속 그 생각뿐이라.",
		"is_decisive": false,
		"options": [
			{"label": "[무슨 생각이요?]", "next_id": "rohan_secret_1"},
			{"label": "[말하기 싫으면 안 해도 돼요]", "next_id": ""},
		],
	},
	{
		"id": "rohan_secret_1",
		"speaker": "로한",
		"text": "오크들 말이야. 처음엔 그냥 사나워진 줄 알았는데... 요즘 보면 뭔가 이상해.",
		"is_decisive": false,
		"next_id": "rohan_secret_2",
	},
	{
		"id": "rohan_secret_2",
		"speaker": "로한",
		"text": "눈빛이... 짐승의 눈빛이 아니야. 뭔가에 쫓기는 것 같은, 그런 눈이더군.",
		"is_decisive": false,
		"options": [
			{"label": "[오크들도 피해자라는 건가요?]", "next_id": "rohan_secret_3"},
			{"label": "[그래도 위험한 건 위험한 거잖아요]", "next_id": "rohan_secret_alt"},
		],
	},
	{
		"id": "rohan_secret_3",
		"speaker": "로한",
		"text": "...그럴지도 모르지. 근데 이런 말 마을에서 함부로 못 해. '괴물 편드는 놈'이라는 소리 듣기 딱 좋으니까.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 3},
		"next_id": "rohan_secret_end",
	},
	{
		"id": "rohan_secret_alt",
		"speaker": "로한",
		"text": "맞아. 그건 그거고. 그래도... 가끔은 마음이 편치 않아.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "rohan", "amount": 2},
		"next_id": "rohan_secret_end",
	},
	{
		"id": "rohan_secret_end",
		"speaker": "로한",
		"text": "아무튼. 자네한테만 하는 말이야. 알겠지?",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_secret_followup",
		"speaker": "로한",
		"text": "오크 얘기, 또 생각났나 보군.",
		"is_decisive": false,
		"options": [
			{"label": "[오크들이 왜 그렇게 됐을까요?]", "next_id": "rohan_secret_followup2"},
			{"label": "[아니, 그냥 안부 물으러 왔어요]", "next_id": ""},
		],
	},
	{
		"id": "rohan_secret_followup2",
		"speaker": "로한",
		"text": "낸들 알겠나. 근데... 숲 저 안쪽, 자네가 아직 안 가본 데서 뭔가 이상한 냄새가 나더군. 타는 냄새 같기도 하고.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "rohan_secret_stage2_1",
		"speaker": "로한",
		"text": "예전? 나도 직접 본 건 아니고... 그런데 우리 집안에 대대로 내려오는 게 하나 있어. 할아버지의 할아버지 때부터, 아니 그보다 더 전부터 이어져온 사냥 기록서야.",
		"is_decisive": false,
		"next_id": "rohan_secret_stage2_2",
	},
	{
		"id": "rohan_secret_stage2_2",
		"speaker": "로한",
		"narration": "(품에서 낡은 책을 꺼내 보여준다)",
		"text": "이 안에 사냥법이며 짐승들 습성이며 다 적혀있는데... 가끔 보면 도무지 믿기지 않는 구절들이 있어.",
		"is_decisive": false,
		"next_id": "rohan_secret_stage2_3",
	},
	{
		"id": "rohan_secret_stage2_3",
		"speaker": "로한",
		"text": "나무 둘레가 어른 셋이 팔을 벌려도 못 감쌀 정도였다느니, 열매 하나가 이만한 크기였다느니. 처음 읽었을 땐 그냥 옛날 사람들 허풍인 줄 알았지.",
		"is_decisive": false,
		"next_id": "rohan_secret_stage2_4",
	},
	{
		"id": "rohan_secret_stage2_4",
		"speaker": "로한",
		"text": "근데 진짜 이상한 건 늑대 얘기야. 지금이야 늑대 한 마리쯤은 나 혼자서도 잡는, 뭐 그런 흔한 짐승 취급이잖아. 근데 기록엔 늑대가 사냥꾼 여럿이 모여야 겨우 잡을 수 있는 아주 강한 짐승으로 나와있어. 한 마리 잡으면 그 고기로 마을 전체가 배불리 먹었다고 적혀있고.",
		"is_decisive": false,
		"next_id": "rohan_secret_stage2_5",
	},
	{
		"id": "rohan_secret_stage2_5",
		"speaker": "로한",
		"narration": "(책을 다시 품에 넣으며)",
		"text": "할아버지도 이 부분 읽을 때마다 고개를 갸웃거리셨어. \"이게 대체 어느 시절 얘기인지, 지금이랑은 너무 안 맞는다\"고. 나도 똑같은 생각이야. 근데 답은 못 찾았지.",
		"set_flag_on_show": "heard_ancient_abundance_hint",
		"is_decisive": false,
		"options": [],
	},
]

# 유서프(떠돌이 상인) 대화 트리
const YUSUF_DIALOGUE: Array = [
	{
		"id": "yusuf_locked_greeting",
		"speaker": "유서프",
		"text": "오, 낯선 얼굴이군? ...아직은 자네한테 해줄 얘기가 없네. 나중에 보지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_greeting",
		"speaker": "유서프",
		"text": "오, 손님이시군! 뭐 필요한 거라도?",
		"text_by_affinity_tier": {
			"npc_id": "yusuf",
			"cold": "...뭐, 필요한 거라도?",
			"neutral": "오, 손님이시군! 뭐 필요한 거라도?",
			"warm": "오, 왔는가! 요즘 자네 얼굴 보는 게 하루의 낙이야.",
			"trusted": "왔군. ...솔직히, 자네한테는 좀 더 솔직해도 될 것 같은데.",
		},
		"is_decisive": false,
		"options": [
			{"label": "[동굴 이야기를 묻는다]", "next_id": "yusuf_cave_hint"},
			{"label": "[당신은 누구세요?]", "next_id": "yusuf_who"},
			{"label": "[뭘 팔고 있어요?]", "next_id": "yusuf_wares"},
			{"label": "[스켈레톤 처치를 돕겠다고 한다]", "next_id": "yusuf_quest_accept", "start_quest": "cave_skeletons", "show_if_quest_inactive": "cave_skeletons"},
			{"label": "[스켈레톤은 어떻게 되어가요?]", "next_id": "yusuf_quest_status", "show_if_quest_active": "cave_skeletons"},
			{"label": "[다른 사람들에 대해 묻는다]", "next_id": "yusuf_gossip", "show_if_flag": "met_elara"},
			{
				"label": "[정말 그냥 상인이 맞아요?]",
				"next_id": "yusuf_secret_stage1",
				"required_affinity": {"npc_id": "yusuf", "min": 50},
				"show_if_not_seen": "yusuf_secret_stage1c",
			},
			{
				"label": "[저번에 물었던 거, 다시 물어봐도 될까요?]",
				"next_id": "yusuf_confession_1",
				"show_if_flag": "part1_reported",
				"show_if_not_seen": "yusuf_confession_end",
			},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "yusuf", "amount": 9, "next_id_success": "yusuf_gift_thanks", "next_id_fail": "yusuf_gift_none"},
			},
		],
	},
	{
		"id": "yusuf_gift_thanks",
		"speaker": "유서프",
		"text": "오, 이런! 장사꾼한테 선물을 다 주시고. 허허, 이 은혜는 잊지 않겠습니다.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_gift_none",
		"speaker": "유서프",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_quest_accept",
		"speaker": "유서프",
		"text": "오, 도와준다니 든든하군! 동굴 입구 쪽에 스켈레톤 셋이 얼쩡거리고 있어. 놈들을 처리해주면 내가 섭섭지 않게 사례하지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_quest_not_ready",
		"speaker": "유서프",
		"text": "아직 준비가 덜 된 것 같군. 먼저 힘을 좀 기르고 오게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_quest_status",
		"speaker": "유서프",
		"text_if_flag": "cave_quest_complete",
		"text": "스켈레톤을 다 정리했다고? 역시 자네야. 약속대로 사례는 톡톡히 하지.",
		"text_false": "아직 동굴에 놈들이 남아있군. 서두르지 말고 확실하게 처리하게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_cave_hint",
		"speaker": "유서프",
		"narration": "(웃음기를 슬쩍 거두며)",
		"text": "동굴 얘기라... 혹시 우물 일 때문에 왔나?",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[네, 다른 마을에서도 이런 일이 있었나요?]", "next_id": "yusuf_cave_hint2"},
		],
	},
	{
		"id": "yusuf_cave_hint2",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 1, "once": true},
		"speaker": "유서프",
		"narration": "(짐 정리하던 손을 잠시 멈춘다)",
		"text": "...있었지. 사실 이번이 처음 듣는 얘기가 아니야.",
		"is_decisive": false,
		"next_id": "yusuf_cave_hint3",
	},
	{
		"id": "yusuf_cave_hint3",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 1, "once": true},
		"speaker": "유서프",
		"text": "두어 달 전에, 여기서 한참 남쪽에 있는 마을에 들렀었거든. 거기서도 똑같은 얘기를 들었어. 우물이 하룻밤 새 마르고, 다들 이상한 빛을 봤다고. 그때는 그냥 흔한 미신이겠거니 하고 넘겼는데.",
		"is_decisive": false,
		"options": [
			{"label": "[거기는 어떻게 됐어요?]", "next_id": "yusuf_cave_q2"},
		],
	},
	{
		"id": "yusuf_cave_q2",
		"speaker": "유서프",
		"text": "몰라. 나는 사흘 정도 머물다가 다음 마을로 떠났으니까. 지나가는 상인이 거기까지 신경 쓸 처지는 아니지 않나.",
		"is_decisive": false,
		"options": [
			{"label": "[유서프 씨는 왜 이 마을에 온 거예요?]", "next_id": "yusuf_cave_q3"},
		],
	},
	{
		"id": "yusuf_cave_q3",
		"speaker": "유서프",
		"narration": "(어깨를 으쓱)",
		"text": "장사꾼이 마을에 오는 이유야 뻔하지, 팔 것도 있고 살 것도 있고. ...근데 뭐, 솔직히 말하면 요즘 내 발걸음이 자꾸 이런 마을들로 향하는 것 같긴 하더군. 물이 안 좋은 곳들 말이야.",
		"is_decisive": false,
		"options": [
			{"label": "[그게 무슨 말이에요?]", "next_id": "yusuf_cave_end"},
		],
	},
	{
		"id": "yusuf_cave_end",
		"speaker": "유서프",
		"narration": "(다시 짐 정리를 시작하며, 말을 돌리듯)",
		"text": "별 뜻 없어. 그냥 우연이겠지. 그보다, 로한이나 미아한테는 가봤나? 그쪽이 더 도움될 거야. 나야 뭐, 지나가는 사람 얘기밖에 못 해주니까.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_who",
		"speaker": "유서프",
		"text": "그냥... 이곳저곳 떠도는 상인이지. 그 이상은... 훗날 알게 될 걸세.",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[수상한데요?]", "next_id": "yusuf_who_suspicious"},
			{"label": "[알겠어요, 안 물어볼게요]", "next_id": ""},
		],
	},
	{
		"id": "yusuf_who_suspicious",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 1, "once": true},
		"speaker": "유서프",
		"text": "수상하다니, 섭섭한걸. ...뭐, 완전히 틀린 말은 아니지만.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_wares",
		"speaker": "유서프",
		"text": "이것저것 있지. 다른 마을에서 가져온 물건들이야.",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[물건을 산다]", "open_shop": true},
			{"label": "[다른 마을은 어떤가요?]", "next_id": "yusuf_other_villages"},
			{"label": "[딱히 필요한 건 없어요]", "next_id": ""},
		],
	},
	{
		"id": "yusuf_other_villages",
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 1, "once": true},
		"speaker": "유서프",
		"text": "여기보단... 힘든 곳도 있더군. 자네 마을은 아직 운이 좋은 편이야.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_gossip",
		"speaker": "유서프",
		"text": "[다른 사람들에 대해 물어본다]",
		"is_decisive": false,
		"options": [
			{"label": "[엘라라는 어떤 분인가요?]", "next_id": "yusuf_about_elara", "show_if_flag": "met_elara"},
			{"label": "[로한을 아세요?]", "next_id": "yusuf_about_rohan", "show_if_flag": "met_rohan"},
		],
	},
	{
		"id": "yusuf_about_elara",
		"speaker": "유서프",
		"text": "장로님? 이 마을에서 제일 지혜로운 분이지. 나도 여러 번 신세를 졌어.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_about_rohan",
		"speaker": "유서프",
		"text": "그 사냥꾼 말인가? 성격은 까칠해도 믿을 만한 사람이야.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "yusuf_secret_stage1",
		"speaker": "유서프",
		"text": "...날카롭구먼. 뭐, 완전히 틀린 말은 아니야.",
		"is_decisive": false,
		"options": [
			{"label": "[역시 뭔가 있었네요]", "next_id": "yusuf_secret_stage1b"},
			{"label": "[그럼 뭔데요?]", "next_id": "yusuf_secret_stage1b"},
		],
	},
	{
		"id": "yusuf_secret_stage1b",
		"speaker": "유서프",
		"text": "난... 그냥 물건을 파는 사람이 아니야. 정확히는, 세상 곳곳을 돌아다니며 뭔가를 '지켜보는' 사람에 가깝지.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "yusuf", "amount": 2},
		"next_id": "yusuf_secret_stage1c",
	},
	{
		"id": "yusuf_secret_stage1c",
		"speaker": "유서프",
		"text": "이 정도만 말해두지. 더 궁금하면... 나를 좀 더 믿게 되면 그때 얘기하세.",
		"is_decisive": false,
		"options": [],
	},
	# --- 씬9: 유서프 재대면 (Part2 오프닝, part1_reported 직후) ---
	{
		"id": "yusuf_confession_1",
		"speaker": "유서프",
		"narration": "(표정이 살짝 굳는다)",
		"text": "...그래, 올 줄 알았어. 무슨 일이 있었는지 말해봐.",
		"is_decisive": false,
		"options": [
			{"label": "[가디언... 아니, 그 사람이 사라지기 전에 이런 말을 했어요. \"감시자들은... 지하에 있다\"고.]", "next_id": "yusuf_confession_2"},
		],
	},
	{
		"id": "yusuf_confession_2",
		"speaker": "유서프",
		"narration": "(숨을 크게 들이쉰다)",
		"text": "...그렇군. 결국 여기서도.",
		"is_decisive": false,
		"next_id": "yusuf_confession_3",
	},
	{
		"id": "yusuf_confession_3",
		"speaker": "유서프",
		"narration": "(한참 침묵하다)",
		"text": "...좋아. 이제 진짜로 말해야 할 때가 됐나 보군. 자네한테 한 번도 얘기 안 한 게 있어.",
		"is_decisive": false,
		"options": [
			{"label": "[뭔데요?]", "next_id": "yusuf_confession_4"},
		],
	},
	{
		"id": "yusuf_confession_4",
		"speaker": "유서프",
		"text": "나, 사실 그냥 떠돌이 장사꾼이 아니야. 예전에... '감시자'라고 불리는 사람들 밑에서 일한 적이 있어.",
		"is_decisive": false,
		"next_id": "yusuf_confession_5",
	},
	{
		"id": "yusuf_confession_5",
		"speaker": "유서프",
		"text": "처음엔 나쁜 일인 줄도 몰랐어. \"맥이 마르는 마을들을 돌보는 일\"이라고 했거든. 근데 어느 마을에서, 그 \"필터\"라는 걸 직접 봤어. 다들 그냥 오래된 장치라고 부르는 그거.",
		"is_decisive": false,
		"next_id": "yusuf_confession_6",
	},
	{
		"id": "yusuf_confession_6",
		"speaker": "유서프",
		"narration": "(사이)",
		"text": "근데 그거, 장치가 아니었어. 안에 사람이 있었어. 움직이지도, 말도 제대로 못 하는데... 눈빛만은 살아있더군. 괴로워하고 있다는 걸, 나는 알 수 있었어.",
		"is_decisive": false,
		"next_id": "yusuf_confession_7",
	},
	{
		"id": "yusuf_confession_7",
		"speaker": "유서프",
		"text": "그날 밤에 도망쳤어. 그 뒤로 이 마을 저 마을 떠돌면서... 뭘 찾고 있었는지 나도 몰라. 근데 이 마을 와서 동굴 사건 얘기를 듣는 순간, 등골이 서늘하더군. 여기서도 똑같은 일이 벌어지고 있었던 거야.",
		"is_decisive": false,
		"next_id": "yusuf_confession_8",
	},
	{
		"id": "yusuf_confession_8",
		"speaker": "유서프",
		"text": "근데 사실, 나도 다는 몰라. 내가 있을 때, 위에 있는 사람들이 하는 말들, 조각조각 주워들은 게 다야.",
		"is_decisive": false,
		"next_id": "yusuf_confession_9",
	},
	{
		"id": "yusuf_confession_9",
		"speaker": "유서프",
		"text": "그 사람들, 뭔가를 계속 \"회수\"한다고 했어. 정확히 뭘 회수하는 건지, 어디로 보내는 건지는 말 안 해줬지. 나 같은 말단은 알 필요 없다는 식이었어.",
		"is_decisive": false,
		"next_id": "yusuf_confession_10",
	},
	{
		"id": "yusuf_confession_10",
		"speaker": "유서프",
		"text": "근데 딱 한 번, 술에 취한 감독관 하나가 이런 말을 흘린 적이 있어. \"저 밑에 가면, 위에서 상상도 못 할 게 있다\"고. 그러고 바로 입을 다물더군.",
		"is_decisive": false,
		"options": [
			{"label": "[저 밑이라면... 지하요?]", "next_id": "yusuf_confession_11"},
			{"label": "[혹시 그것 때문에 물지기가 필요한 거예요?]", "next_id": "yusuf_confession_11"},
		],
	},
	{
		"id": "yusuf_confession_11",
		"speaker": "유서프",
		"narration": "(고개를 끄덕인다)",
		"text": "그때는 무슨 소리인지 몰랐는데, 지금 자네 얘기 들으니까... 소름이 돋는군.",
		"is_decisive": false,
		"next_id": "yusuf_confession_12",
	},
	{
		"id": "yusuf_confession_12",
		"speaker": "유서프",
		"text": "생각해봐. 물지기가 마을 맥을 줄이고 있다는 건 이제 확실해. 근데 줄어든 만큼 그 맥이 그냥 사라지는 게 아니라면? 어디론가 가고 있는 거라면?",
		"is_decisive": false,
		"next_id": "yusuf_confession_13",
	},
	{
		"id": "yusuf_confession_13",
		"speaker": "유서프",
		"narration": "(스스로도 믿기지 않는다는 듯)",
		"text": "...설마, 그 지하라는 데로? 그 사람들이, 그동안 계속... 맥을 빼돌리고 있었던 건가?",
		"is_decisive": false,
		"options": [
			{"label": "[근데 왜요? 그렇게까지 해서 뭘 얻으려고요?]", "next_id": "yusuf_confession_14"},
		],
	},
	{
		"id": "yusuf_confession_14",
		"speaker": "유서프",
		"narration": "(고개를 젓는다)",
		"text": "그것까진 나도 몰라. 권력? 돈? ...아니면 훨씬 더 큰 뭔가일 수도 있고. 맥이 그냥 자원이 아니라 생명의 근원이라면, 그걸 쌓아서 뭘 하려는 건지 상상하기도 무서워.",
		"is_decisive": false,
		"next_id": "yusuf_confession_15",
	},
	{
		"id": "yusuf_confession_15",
		"speaker": "유서프",
		"narration": "(플레이어를 본다)",
		"text": "근데 짐작만으론 아무것도 못 해. 증거가 필요해.",
		"is_decisive": false,
		"options": [
			{"label": "[증거요?]", "next_id": "yusuf_confession_16"},
		],
	},
	{
		"id": "yusuf_confession_16",
		"speaker": "유서프",
		"text": "여기 물지기는 이제 사라졌잖아. 직접 물어볼 수도 없고. 근데... 이미 완전히 말라버린 마을들, 사막이 된 곳들에는 아직 물지기 껍데기가 남아있을 거야. 거기 가면 뭐라도 나올지 몰라.",
		"is_decisive": false,
		"next_id": "yusuf_confession_17",
	},
	{
		"id": "yusuf_confession_17",
		"speaker": "유서프",
		"text": "문제는 거기가 바다 건너에 있다는 거야. 마을 부두에 배가 한 척 있다고 들었어. 그거 타면 갈 수 있을 거야.",
		"is_decisive": false,
		"options": [
			{"label": "[같이 가는 거예요?]", "next_id": "yusuf_confession_end"},
		],
	},
	{
		"id": "yusuf_confession_end",
		"speaker": "유서프",
		"narration": "(씁쓸하게 웃는다)",
		"text": "나도 이제 와서 발 빼기엔 너무 멀리 왔지. ...그래, 같이 가자. 이번엔 도망 안 쳐.",
		"set_flag_on_show": "yusuf_full_confession",
		"is_decisive": false,
		"options": [],
	},
]

# 씬10-B: 사막에 동행한 유서프의 짧은 반응 대사 (나딤 대사는 그대로, 이건 별도 NPC로 배치)
const YUSUF_DESERT_DIALOGUE: Array = [
	{
		"id": "yusuf_desert_greeting",
		"speaker": "유서프",
		"narration": "(손차양을 하며)",
		"text": "여기도... 마을이었던 곳이겠지. 이제 기억하는 사람도 없겠지만.",
		"is_decisive": false,
		"options": [
			{"label": "[여기도 물지기가 있었어요?]", "next_id": "yusuf_desert_warden"},
			{"label": "[알겠어요]", "next_id": ""},
		],
	},
	{
		"id": "yusuf_desert_warden",
		"speaker": "유서프",
		"narration": "(말끝을 흐린다)",
		"text": "있었겠지. 근데 아마 지금은...",
		"is_decisive": false,
		"options": [],
	},
]

# 씬12: 유적 필터룸 — 벽화 리빌 + 물지기 봉인 해제 [truth_revealed]
const FILTER_ROOM_DIALOGUE: Array = [
	{
		"id": "filter_room_1",
		"speaker": "",
		"text": "",
		"narration": "첫 번째 벽화. 물이 넘쳐흐르는 땅. 사람들이 웃고 있다. 나무는 지금 것보다 훨씬 크고, 강은 은빛으로 빛난다.",
		"is_decisive": false,
		"next_id": "filter_room_2",
	},
	{
		"id": "filter_room_2",
		"speaker": "유서프",
		"narration": "(벽화를 손으로 쓸며)",
		"text": "...이게, 옛날 모습이라는 건가.",
		"is_decisive": false,
		"next_id": "filter_room_3",
	},
	{
		"id": "filter_room_3",
		"speaker": "",
		"text": "",
		"narration": "두 번째 벽화. 사람들이 한 사람을 에워싸고 있다. 그 사람이 빛 속으로 가라앉는다. 주변 사람들의 표정엔 두려움과 슬픔이 뒤섞여 있다.",
		"is_decisive": false,
		"options": [
			{"label": "[이게... 물지기가 처음 생겨난 순간인가요?]", "next_id": "filter_room_4"},
		],
	},
	{
		"id": "filter_room_4",
		"speaker": "유서프",
		"narration": "(침묵하다)",
		"text": "...아마도.",
		"is_decisive": false,
		"next_id": "filter_room_5",
	},
	{
		"id": "filter_room_5",
		"speaker": "",
		"text": "",
		"narration": "세 번째 벽화. 지하로 이어지는 계단. 그 아래, 왕관 같은 걸 쓴 형체들이 빛나는 물줄기를 손에 쥐고 있다. 늙지 않는 얼굴로.",
		"is_decisive": false,
		"next_id": "filter_room_6",
	},
	{
		"id": "filter_room_6",
		"speaker": "유서프",
		"narration": "(숨을 삼킨다)",
		"text": "...저게, 감시자인가.",
		"is_decisive": false,
		"options": [
			{"label": "[저 사람들, 늙지를 않네요.]", "next_id": "filter_room_7"},
		],
	},
	{
		"id": "filter_room_7",
		"speaker": "유서프",
		"narration": "(떨리는 목소리로)",
		"text": "...그러니까 이거였구나. 맥을 뺏어서... 저 사람들, 영원히 살려고 그런 거였어.",
		"is_decisive": false,
		"next_id": "filter_room_8",
	},
	{
		"id": "filter_room_8",
		"speaker": "",
		"text": "",
		"narration": "방 한가운데, 이미 오래전에 활동을 멈춘 물지기의 껍데기가 놓여 있다. 저항의 흔적도, 몸부림의 흔적도 없다. 그저 텅 비어있을 뿐이다.",
		"is_decisive": false,
		"options": [
			{"label": "[여기 물지기는... 이미]", "next_id": "filter_room_9"},
		],
	},
	{
		"id": "filter_room_9",
		"speaker": "유서프",
		"narration": "(조용히)",
		"text": "응. 여긴 벌써 오래전에 다 뽑혔어. 싸울 힘도 남아있지 않았겠지.",
		"is_decisive": false,
		"options": [
			{"label": "[그럼 우리가 할 수 있는 건...]", "next_id": "filter_room_10"},
		],
	},
	{
		"id": "filter_room_10",
		"speaker": "유서프",
		"text": "봉인을 풀어주는 것 정도. 그거라도 해주자.",
		"is_decisive": false,
		"options": [
			{"label": "[봉인 해제]", "next_id": "filter_room_release"},
		],
	},
	{
		"id": "filter_room_release",
		"speaker": "",
		"text": "",
		"narration": "봉인이 풀리자, 껍데기가 조용히 빛의 먼지로 흩어진다. 저항도, 마지막 말도 없다. 그저 아주 오랫동안 미뤄졌던 게 이제야 끝난 것처럼.",
		"is_decisive": false,
		"next_id": "filter_room_waterburst",
	},
	{
		"id": "filter_room_waterburst",
		"speaker": "",
		"text": "",
		"narration": "그 순간, 마을에서 봤던 것과 똑같은 광경이 펼쳐진다. 벽 틈에서 맥이 터져 나오기 시작한다. 고대의 색과 밝기를 그대로 간직한 채.",
		"is_decisive": false,
		"next_id": "filter_room_11",
	},
	{
		"id": "filter_room_11",
		"speaker": "유서프",
		"narration": "(넋을 잃고 바라보며)",
		"text": "...이만큼이나. 이 정도였다니.",
		"set_flag_on_show": "truth_revealed",
		"is_decisive": false,
		"options": [
			{"label": "[이제 어떡하죠?]", "next_id": "filter_room_12"},
		],
	},
	{
		"id": "filter_room_12",
		"speaker": "유서프",
		"narration": "(플레이어를 본다)",
		"text": "이제 확실해졌으니까... 남은 건 하나뿐이야. 저 지하로 가는 거.",
		"is_decisive": false,
		"next_id": "filter_room_end",
	},
	{
		"id": "filter_room_end",
		"speaker": "유서프",
		"narration": "(씁쓸하게, 그러나 단단하게)",
		"text": "이번엔 나도 도망 안 쳐. 끝까지 같이 가자.",
		"is_decisive": false,
		"options": [],
	},
]

# 미아(아이) 대화 트리
const MIA_DIALOGUE: Array = [
	{
		"id": "mia_locked_greeting",
		"speaker": "미아",
		"text": "...",
		"narration": "(낯선 사람을 경계하며 뒤로 물러선다)",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_greeting",
		"speaker": "미아",
		"narration": "(마을 외곽, 담벼락 아래 — 미아가 혼자 쪼그려 앉아 땅에 나뭇가지로 뭔가를 그리고 있다. 인기척에 흠칫하며 그림을 슥슥 지운다) (작게, 경계하며)",
		"text": "...누구세요.",
		"is_decisive": false,
		"options": [
			{"label": "[괜찮아? 여기서 뭐 해?]", "next_id": "mia_q1"},
			{"label": "[그냥 인사만 한다]", "next_id": "mia_smalltalk", "show_if_flag": "met_mia"},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "mia", "amount": 9, "next_id_success": "mia_gift_thanks", "next_id_fail": "mia_gift_none"},
			},
		],
	},
	{
		"id": "mia_q1",
		"speaker": "미아",
		"narration": "(아직 경계하며)",
		"text": "...그냥요. 마을 사람... 아니죠?",
		"is_decisive": false,
		"options": [
			{"label": "[응, 며칠 전에 왔어. 근데 진짜 여기서 뭐 하고 있었어?]", "next_id": "mia_q2"},
		],
	},
	{
		"id": "mia_q2",
		"speaker": "미아",
		"narration": "(조금 누그러지며)",
		"text": "...나비 찾고 있었어요. 제 고양이요. 어제부터 안 보여서.",
		"is_decisive": false,
		"options": [
			{"label": "[나비, 이름 예쁘다. 원래 여기서 자주 놀아?]", "next_id": "mia_q3"},
		],
	},
	{
		"id": "mia_q3",
		"speaker": "미아",
		"narration": "(살짝 웃는 듯하다가 다시 굳는다)",
		"text": "...아니요. 여긴 잘 안 와요. 그냥... 나비 찾다 보니까 여기까지 왔어요.",
		"is_decisive": false,
		"options": [
			{"label": "[그날 밤에도 나비 찾으러 나갔었어?]", "next_id": "mia_q4"},
		],
	},
	{
		"id": "mia_q4",
		"speaker": "미아",
		"narration": "(움찔하며 뒤로 물러난다)",
		"text": "...어떻게 알아요?",
		"is_decisive": false,
		"options": [
			{"label": "[엘라라 촌장님한테 들었어. 걱정 많이 하시더라, 너희 어머니도.]", "next_id": "mia_q5"},
		],
	},
	{
		"id": "mia_q5",
		"speaker": "미아",
		"narration": "(시선을 피하며, 목소리가 작아진다) (말을 흐리며 무릎 사이에 얼굴을 파묻는다)",
		"text": "...그날도, 나비가 안 보여서... 원래 밤에 잠이 잘 안 와서 가끔 몰래 나가거든요. 근데 그날은 나비 우는 소리가 들리는 것 같아서 동굴 쪽까지 갔었어요.",
		"is_decisive": false,
		"options": [
			{"label": "[...괜찮아, 무리해서 말 안 해도 돼]", "next_id": "mia_q6"},
		],
	},
	{
		"id": "mia_q6",
		"speaker": "미아",
		"narration": "(고개를 든다, 눈이 살짝 붉다)",
		"text": "...진짜요?",
		"is_decisive": false,
		"next_id": "mia_approach_press",
	},
	{
		"id": "mia_gift_thanks",
		"speaker": "미아",
		"text": "우와... 나 주는 거예요? 헤헤, 고마워요! 소중히 간직할게요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_gift_none",
		"speaker": "미아",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_approach_press",
		"speaker": "미아",
		"narration": "(미아가 뭔가 더 말하려다, 망설인다)",
		"text": "",
		"is_decisive": true,
		"options": [
			{"label": "[아니, 사실대로 말해줘. 중요한 일이야]", "next_id": "mia_scared", "flag_to_set": "earned_mia_trust", "flag_value": false},
			{"label": "[...응, 진짜야. 천천히 얘기해도 돼]", "next_id": "mia_relieved", "flag_to_set": "earned_mia_trust", "flag_value": true},
		],
	},
	{
		"id": "mia_scared",
		"speaker": "미아",
		"narration": "(눈을 크게 뜨고 몸을 움츠린다) (양팔로 무릎을 감싸 안는다)",
		"text": "...몰라요. 아무것도 못 봤어요.",
		"set_flag_on_show": "met_mia_decisive",
		"is_decisive": false,
		"options": [
			{"label": "[미안, 다그치려던 건 아니었어]", "next_id": "mia_scared_apology"},
			{"label": "[...알겠어]", "next_id": ""},
		],
	},
	{
		"id": "mia_scared_apology",
		"speaker": "미아",
		"narration": "(고개를 돌린 채) (한참 침묵하다가, 아주 작게)",
		"text": "...괜찮아요. ...그냥, 파란 빛. 그거 봤어요. 그게 다예요. 더는... 말하기 싫어요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_relieved",
		"speaker": "미아",
		"narration": "(조금 안심한 듯, 그래도 여전히 조심스럽게)",
		"text": "...진짜 아무한테도 말 안 할 거예요? 어른들은 다 저보고 무서워서 헛것 봤다고 그래요.",
		"set_flag_on_show": "met_mia_decisive",
		"is_decisive": false,
		"options": [
			{"label": "[응, 약속할게. 네가 본 거 그대로 믿을게]", "next_id": "mia_relieved_reveal"},
		],
	},
	{
		"id": "mia_relieved_reveal",
		"speaker": "미아",
		"narration": "(숨을 한 번 크게 쉬고)",
		"text": "...그날, 나비 쫓아서 동굴 어귀까지 갔었어요. 거기 오래된 돌 있는 데까지요. 근데 갑자기 땅이 흔들리고, 동굴 안에서 파란 빛이 확 새어나왔어요.",
		"is_decisive": false,
		"options": [
			{"label": "[무섭지 않았어?]", "next_id": "mia_relieved_detail"},
		],
	},
	{
		"id": "mia_relieved_detail",
		"speaker": "미아",
		"text": "처음엔 무서웠는데... 근데 그 빛이랑 같이 소리가 들렸어요. 낮게, 오래오래 이어지는 소리요. 무서운 소리가 아니라... 꼭 누가 우는 소리 같았어요. 사람이 우는 소리요. 그래서 더 무서웠던 것 같아요. 왜 그런 게 저 안에서 우는 건지 몰라서.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_smalltalk",
		"speaker": "미아",
		"text": "...",
		"narration": "(미아가 예전보다 편하게 쳐다본다)",
		"is_decisive": false,
		"options": [
			{
				"label": "[요즘 어때?]",
				"next_id": "mia_smalltalk_ok",
				"next_id_by_affinity": {
					"npc_id": "mia",
					"thresholds": [40, 70],
					"next_ids": ["mia_smalltalk_shy", "mia_smalltalk_ok", "mia_smalltalk_close"],
				},
			},
			{
				"label": "[그 꿈 이야기, 좀 더 해줄래?]",
				"next_id": "mia_dream_intro",
				"required_affinity": {"npc_id": "mia", "min": 60},
				"show_if_flag": "earned_mia_trust",
				"show_if_not_seen": "mia_dream_end",
			},
			{
				"label": "[요즘도 그 꿈을 꿔?]",
				"next_id": "mia_dream_followup",
				"show_if_seen": "mia_dream_end",
			},
		],
	},
	{
		"id": "mia_smalltalk_shy",
		"speaker": "미아",
		"text": "...그냥 그래요.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "mia", "amount": 1},
		"options": [],
	},
	{
		"id": "mia_smalltalk_ok",
		"speaker": "미아",
		"text": "이제 무섭지 않아요. 당신 덕분에요.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "mia", "amount": 2},
		"options": [],
	},
	{
		"id": "mia_smalltalk_close",
		"speaker": "미아",
		"text": "당신이 오면 좋아요. 얘기할 사람이 생긴 것 같아서.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "mia", "amount": 3},
		"options": [],
	},
	{
		"id": "mia_dream_intro",
		"speaker": "미아",
		"text": "...그거요? 사실 그날 밤 말고도, 예전부터 이상한 꿈을 꿨어요.",
		"is_decisive": false,
		"options": [
			{"label": "[어떤 꿈인데?]", "next_id": "mia_dream_1"},
			{"label": "[괜찮으면 말 안 해도 돼]", "next_id": ""},
		],
	},
	{
		"id": "mia_dream_1",
		"speaker": "미아",
		"text": "물이... 빛나는 꿈이에요. 근데 슬픈 빛이었어요. 꼭 뭔가를 찾고 있는 것처럼.",
		"is_decisive": false,
		"next_id": "mia_dream_2",
	},
	{
		"id": "mia_dream_2",
		"speaker": "미아",
		"text": "엄마는 그냥 애가 꾸는 꿈이라고 했는데... 그날 밤 진짜로 그 빛을 봤을 때, 무서웠던 것보다 익숙하다는 느낌이 더 컸어요.",
		"is_decisive": false,
		"affinity_change_on_show": {"npc_id": "mia", "amount": 4},
		"next_id": "mia_dream_end",
	},
	{
		"id": "mia_dream_end",
		"speaker": "미아",
		"text": "...이상하죠? 아무튼, 당신한테는 말할 수 있어서 다행이에요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_dream_followup",
		"speaker": "미아",
		"text": "요즘도 가끔 그 꿈을 꿔요. 근데... 요즘은 배경이 달라요. 물 대신 온통 모래인 곳이에요.",
		"is_decisive": false,
		"next_id": "mia_dream_followup2",
	},
	{
		"id": "mia_dream_followup2",
		"speaker": "미아",
		"narration": "(인형을 꼭 안으며)",
		"text": "예전엔 그냥 반짝이는 물이 슬퍼 보이기만 했는데... 요즘은, 누가 우는 소리도 들려. 꿈속에서.",
		"is_decisive": false,
		"next_id": "mia_dream_followup3",
	},
	{
		"id": "mia_dream_followup3",
		"speaker": "미아",
		"narration": "(작은 목소리로)",
		"text": "근데 엄마한테 말하면 또 \"그냥 꿈이야\" 그러겠지. ...당신도 그렇게 생각해?",
		"is_decisive": false,
		"options": [
			{"label": "[아니, 진짜였을 수도 있어]", "next_id": "mia_dream_followup_yes"},
			{"label": "[글쎄, 꿈은 꿈이니까]", "next_id": "mia_dream_followup_no"},
		],
	},
	{
		"id": "mia_dream_followup_yes",
		"speaker": "미아",
		"text": "...정말요? 그렇게 말해주니까 좀 안심돼요.",
		"affinity_change_on_show": {"npc_id": "mia", "amount": 2},
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "mia_dream_followup_no",
		"speaker": "미아",
		"text": "...역시 그런가요. ...그냥 그런 거겠죠, 뭐.",
		"affinity_change_on_show": {"npc_id": "mia", "amount": -1},
		"is_decisive": false,
		"options": [],
	},
]

# 카밀(감시자 동료) 대화 트리 — 유서프가 정체를 밝힌 뒤(yusuf_secret_stage2를 본 뒤) 마을에 등장.
# "지금 갈게요"를 고르면 kamil_confirm_departure에 도달하며, 그 노드의 set_flag_on_show로 boat_available이 켜진다
const KAMIL_DIALOGUE: Array = [
	{
		"id": "kamil_greeting",
		"speaker": "카밀",
		"text": "...당신이군요. 유서프가 말한 그 사람.",
		"is_decisive": false,
		"options": [
			{"label": "[당신은 누구세요?]", "next_id": "kamil_intro_1"},
			{"label": "[왜 저를 기다렸나요?]", "next_id": "kamil_intro_1"},
			{
				"label": "[나딤을 아세요?]",
				"next_id": "kamil_sister_intro",
				"required_affinity": {"npc_id": "kamil", "min": 55},
			},
			{
				# 2부 결정적 선택: 유적 보스를 처치하고 진실까지 알아낸 뒤에만, 그리고 아직 이 갈래를 안 봤을 때만 열린다
				"label": "[유적에서 알게 된 걸 말한다]",
				"next_id": "kamil_truth_1",
				"show_if_flags": ["ruins_boss_defeated", "truth_revealed"],
				"show_if_not_seen": "kamil_truth_1",
			},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "kamil", "amount": 9, "next_id_success": "kamil_gift_thanks", "next_id_fail": "kamil_gift_none"},
			},
		],
	},
	# --- 카밀 자매 갈래 (호감도 55+) : 카밀과 나딤은 자매 ---
	{
		"id": "kamil_sister_intro",
		"speaker": "카밀",
		"text": "...그 이름을 어떻게. 아, 사막에서 만났겠군.",
		"is_decisive": false,
		"next_id": "kamil_sister_1",
	},
	{
		"id": "kamil_sister_1",
		"speaker": "카밀",
		"text": "그 애는... 제 동생입니다. 오래전에 서로 다른 길을 택했죠.",
		"is_decisive": false,
		"next_id": "kamil_sister_2",
	},
	{
		"id": "kamil_sister_2",
		"speaker": "카밀",
		"text": "저는 떠났고, 그 애는 남았어요. 그 애는 아직도 저를 원망할지도 모르겠네요.",
		"affinity_change_on_show": {"npc_id": "kamil", "amount": 3, "once": true},
		"is_decisive": false,
		"options": [],
	},
	# --- 2부 결정적 선택 갈래 (유적의 진실을 카밀에게 알린 뒤) ---
	{
		"id": "kamil_truth_1",
		"speaker": "카밀",
		"narration": "(표정을 살피며)",
		"text": "...봤군요. 벽화.",
		"is_decisive": false,
		"options": [
			{"label": "[당신, 알고 있었던 거예요?]", "next_id": "kamil_truth_1b"},
		],
	},
	{
		"id": "kamil_truth_1b",
		"speaker": "카밀",
		"narration": "(침묵하다)",
		"text": "...조금은요. 전부는 아니지만.",
		"is_decisive": false,
		"next_id": "kamil_truth_1c",
	},
	{
		"id": "kamil_truth_1c",
		"speaker": "카밀",
		"text": "저도 그쪽 사람이에요. 감시자요. 근데... 동생 만나고 나서부터, 계속 마음이 편치 않았어요. 배 태워주는 것 정도는 괜찮겠지, 하고 넘어온 것도 사실 스스로 생각해도 이상했고요.",
		"is_decisive": false,
		"options": [
			{"label": "[그럼 도와줄 수 있어요? 지하로 가는 방법.]", "next_id": "kamil_truth_2"},
		],
	},
	{
		"id": "kamil_truth_2",
		"speaker": "카밀",
		"narration": "(망설이다)",
		"text": "...알아요. 들어가는 길. 안에 구조도 어느 정도는. 근데... 저를 믿고 그 정보를 받을지는, 당신이 정하세요.",
		"is_decisive": false,
		"next_id": "kamil_truth_3",
	},
	{
		"id": "kamil_truth_3",
		"speaker": "카밀",
		"text": "저는 아직 그쪽 사람이에요. 제가 드리는 정보가 진짜인지, 혹시 함정은 아닌지, 저도 백 퍼센트 장담은 못 해요.",
		"is_decisive": true,
		"options": [
			{"label": "[당신을 믿고 도움을 받는다]", "next_id": "kamil_choice_reveal", "flag_to_set": "truth_revealed", "flag_value": true},
			{"label": "[거절하고 우리끼리 알아낸다]", "next_id": "kamil_choice_secret", "flag_to_set": "truth_revealed", "flag_value": false},
		],
	},
	{
		"id": "kamil_choice_reveal",
		"speaker": "카밀",
		"narration": "(안도한 듯, 그러나 무거운 표정으로)",
		"text": "...고마워요. 후회 안 하게 할게요. 지하로 가는 입구, 제가 아는 데까지는 안내할게요.",
		"set_flag_on_show": "part2_complete", # 이 노드에 도달하면 2부 완료 — 대화 종료 시 kamil_npc가 최종 엔딩으로 전환
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kamil_choice_secret",
		"speaker": "카밀",
		"narration": "(씁쓸하게 웃는다)",
		"text": "...그렇겠죠. 당연해요. 그래도 조심하세요. 저 없이 들어가는 건... 훨씬 위험할 거예요.",
		"set_flag_on_show": "part2_complete", # 이 노드에 도달하면 2부 완료 — 대화 종료 시 kamil_npc가 최종 엔딩으로 전환
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kamil_gift_thanks",
		"speaker": "카밀",
		"text": "...저에게요? 뜻밖이군요. 이런 걸 받아본 게 얼마 만인지... 감사합니다.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kamil_gift_none",
		"speaker": "카밀",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kamil_intro_1",
		"speaker": "카밀",
		"text": "...카밀이에요. 유서프랑 비슷한 일을 하는 사람, 정도로만 알아두세요.",
		"is_decisive": false,
		"next_id": "kamil_intro_2",
	},
	{
		"id": "kamil_intro_2",
		"speaker": "카밀",
		"text": "필요한 게 있으면 말씀하세요. 사막 쪽으로 가실 거라면, 배는 준비해둘게요.",
		"is_decisive": false,
		"options": [
			{"label": "[지금 갈게요]", "next_id": "kamil_confirm_departure"},
			{"label": "[아직 준비가 안 됐어요]", "next_id": ""},
		],
	},
	{
		"id": "kamil_confirm_departure",
		"speaker": "카밀",
		"text": "알겠습니다. 부두에서 기다리고 있겠습니다.",
		"is_decisive": false,
		"set_flag_on_show": "boat_available", # 이 노드에 도달하는 순간 부두의 배가 이용 가능해짐
		"options": [],
	},
]

# 나딤(사막 정착지 지도자/생존자) 대화 트리 — 2부 초반. 끝에서 ruins_available를 켜 유적 입구를 연다
const NADIM_DIALOGUE: Array = [
	{
		"id": "nadim_greeting",
		"speaker": "나딤",
		"text_by_affinity_tier": {
			"npc_id": "nadim",
			"cold": "...뭐 필요한 거라도 있나.",
			"neutral": "...또 다른 이방인인가. 카밀이 데려온 건가?",
			"warm": "왔군. 자네가 오면 마음이 조금 놓여.",
			"trusted": "왔나. 요즘은... 자네 덕분에 버티고 있는 것 같아.",
		},
		"text": "...또 다른 이방인인가. 카밀이 데려온 건가?", # tier 조회 실패 시 fallback (기본 = neutral)
		"is_decisive": false,
		"options": [
			{"label": "[네, 도움이 필요하다고 들었어요]", "next_id": "nadim_intro_1"},
			{"label": "[미라 처치를 돕겠다고 한다]", "next_id": "nadim_mummy_accept", "start_quest": "desert_mummies", "show_if_flag": "ruins_available", "show_if_quest_inactive": "desert_mummies"},
			{"label": "[미라는 어떻게 되어가요?]", "next_id": "nadim_mummy_status", "show_if_quest_active": "desert_mummies"},
			{"label": "[유적의 열쇠를 찾아보겠다고 한다]", "next_id": "nadim_key_accept", "start_quest": "ruins_key", "show_if_flag": "ruins_available", "show_if_quest_inactive": "ruins_key"},
			{"label": "[열쇠는 찾았나요?]", "next_id": "nadim_key_status", "show_if_quest_active": "ruins_key"},
			{
				"label": "[미라들에 대해 어떻게 생각하세요?]",
				"next_id": "nadim_secret_intro",
				"required_affinity": {"npc_id": "nadim", "min": 55},
				"show_if_quest_active": "desert_mummies",
			},
			{
				"label": "[카밀을 아세요?]",
				"next_id": "nadim_sister_intro",
				"required_affinity": {"npc_id": "nadim", "min": 55},
			},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "nadim", "amount": 9, "next_id_success": "nadim_gift_thanks", "next_id_fail": "nadim_gift_none"},
			},
		],
	},
	{
		"id": "nadim_gift_thanks",
		"speaker": "나딤",
		"text": "...나한테? 이 삭막한 땅에서 이런 걸 받을 줄은 몰랐군. 고맙네.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "nadim_gift_none",
		"speaker": "나딤",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "nadim_mummy_accept",
		"speaker": "나딤",
		"text": "고맙네. 유적으로 가는 길목에 그 마른 것들이 셋 있어. 놈들이 있는 한 아무도 유적에 닿지 못해. 부디 조심하게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "nadim_mummy_status",
		"speaker": "나딤",
		"text_if_flag": "desert_mummies_complete",
		"text": "미라를 전부 처리했다고? ...자네, 보통이 아니군. 정말 고맙네.",
		"text_false": "아직 그 마른 것들이 남아있군. 무리하지 말게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "nadim_key_accept",
		"speaker": "나딤",
		"text": "열쇠 없이는 유적의 문이 열리지 않아. 이 근처 어딘가에 옛 사람들이 숨겨뒀을 걸세. 잘 찾아보게.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "nadim_key_status",
		"speaker": "나딤",
		"text_if_flag": "ruins_key_complete",
		"text": "열쇠를 찾았군. 그렇다면... 이제 정말 갈 수 있겠어.",
		"text_false": "아직 열쇠를 못 찾았나 보군. 유적의 문은 그것 없이는 꿈쩍도 안 해.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "nadim_intro_1",
		"speaker": "나딤",
		"text": "도움이라... 이미 늦었을지도 모르지만, 그래도 와줘서 고맙네.",
		"is_decisive": false,
		"next_id": "nadim_intro_2",
	},
	{
		"id": "nadim_intro_2",
		"speaker": "나딤",
		"text": "이 땅은 원래 이렇지 않았어. 몇 년 전부터 서서히 말라갔지. 당신네 마을의 우물처럼 말이야.",
		"is_decisive": false,
		"options": [
			{"label": "[여기서 무슨 일이 있었던 건가요?]", "next_id": "nadim_backstory_1"},
			{"label": "[제가 뭘 도우면 될까요?]", "next_id": "nadim_backstory_1"},
		],
	},
	{
		"id": "nadim_backstory_1",
		"speaker": "나딤",
		"text": "이 근처에... 오래된 유적이 있어. 옛 사람들이 물줄기를 다스리던 곳이라고 전해지지.",
		"affinity_change_on_show": {"npc_id": "nadim", "amount": 2, "once": true},
		"is_decisive": false,
		"next_id": "nadim_backstory_2",
	},
	{
		"id": "nadim_backstory_2",
		"speaker": "나딤",
		"text": "그 유적 안쪽에 들어간 사람이 아무도 안 돌아왔어. 그래도... 답을 찾으려면 그곳뿐이라고 생각해.",
		"is_decisive": false,
		"options": [
			{"label": "[제가 가볼게요]", "next_id": "nadim_quest_offer"},
			{"label": "[너무 위험한 거 아닌가요?]", "next_id": "nadim_quest_offer"},
		],
	},
	{
		"id": "nadim_quest_offer",
		"speaker": "나딤",
		"text": "고맙네. 조심하게. 유적 입구는 마을 동쪽에 있어.",
		"set_flag_on_show": "ruins_available", # 이 노드에 도달하는 순간 사막 유적 입구가 이용 가능해짐
		"is_decisive": false,
		"options": [],
	},
	# --- 나딤 비밀 갈래 (호감도 55+, 미라 퀘스트 진행 중일 때) ---
	{
		"id": "nadim_secret_intro",
		"speaker": "나딤",
		"text": "...그 얘기, 언젠가는 물어볼 줄 알았지.",
		"is_decisive": false,
		"options": [
			{"label": "[뭔가 알고 계신 거죠?]", "next_id": "nadim_secret_1"},
		],
	},
	{
		"id": "nadim_secret_1",
		"speaker": "나딤",
		"text": "저 마른 것들 말이야... 원래 이 근처에 흔한 짐승들이었어. 그냥 좀 사나운 정도였지.",
		"is_decisive": false,
		"next_id": "nadim_secret_2",
	},
	{
		"id": "nadim_secret_2",
		"speaker": "나딤",
		"text": "근데 언젠가부터 눈에 띄게 사나워졌어. 이유도 없이 닥치는 대로 달려들고.",
		"affinity_change_on_show": {"npc_id": "nadim", "amount": 3, "once": true},
		"is_decisive": false,
		"next_id": "nadim_secret_3",
	},
	{
		"id": "nadim_secret_3",
		"speaker": "나딤",
		"text": "카밀 같은 이들이 오기 시작한 것도... 그 무렵부터였다는 소문이 있어.",
		"is_decisive": false,
		"options": [
			{"label": "[감시자들이 뭔가 저지른 건가요?]", "next_id": "nadim_secret_4"},
			{"label": "[그냥 소문 아닐까요?]", "next_id": "nadim_secret_alt"},
		],
	},
	{
		"id": "nadim_secret_4",
		"speaker": "나딤",
		"text": "모르지. 확실한 건 아무것도 없어. 그래도... 자네가 유적에 들어가면, 뭔가 알 수 있을지도 모르겠군.",
		"affinity_change_on_show": {"npc_id": "nadim", "amount": 2, "once": true},
		"is_decisive": false,
		"next_id": "nadim_secret_end",
	},
	{
		"id": "nadim_secret_alt",
		"speaker": "나딤",
		"text": "그럴지도. 근데... 이상하게 마음에 걸려서 말이야.",
		"affinity_change_on_show": {"npc_id": "nadim", "amount": 2, "once": true},
		"is_decisive": false,
		"next_id": "nadim_secret_end",
	},
	{
		"id": "nadim_secret_end",
		"speaker": "나딤",
		"text": "이건 카밀한테는 아직 말하지 말게. 확실해지기 전까지는.",
		"is_decisive": false,
		"options": [],
	},
	# --- 나딤 자매 갈래 (호감도 55+) : 카밀과 나딤은 자매 ---
	{
		"id": "nadim_sister_intro",
		"speaker": "나딤",
		"text": "...언니 얘기를 하는군.",
		"is_decisive": false,
		"next_id": "nadim_sister_1",
	},
	{
		"id": "nadim_sister_1",
		"speaker": "나딤",
		"text": "우리는 자매였어. 언니는 떠나는 쪽을 택했고, 난 남는 쪽을 택했지.",
		"is_decisive": false,
		"next_id": "nadim_sister_2",
	},
	{
		"id": "nadim_sister_2",
		"speaker": "나딤",
		"text": "가끔은... 언니가 옳았을지도 모른다는 생각이 들어. 하지만 난 후회 안 해.",
		"affinity_change_on_show": {"npc_id": "nadim", "amount": 3, "once": true},
		"is_decisive": false,
		"options": [],
	},
]

# 카심(정체를 숨긴 무기 상인, 술집 상주) 대화 트리
const KASIM_DIALOGUE: Array = [
	{
		"id": "kasim_greeting",
		"speaker": "카심",
		"text": "...손님인가. 후드 밑으로 눈을 마주치긴 좀 그렇지만, 뭐, 장사는 장사니까.",
		"is_decisive": false,
		"options": [
			{"label": "[뭘 파세요?]", "next_id": "kasim_wares"},
			{"label": "[누구세요?]", "next_id": "kasim_intro_1"},
			{
				"label": "[장사는 잘 되세요?]",
				"next_id": "kasim_smalltalk_1",
				"required_affinity": {"npc_id": "kasim", "min": 50},
			},
			{
				"label": "[선물을 준다]",
				"give_gift": {"npc_id": "kasim", "amount": 9, "next_id_success": "kasim_gift_thanks", "next_id_fail": "kasim_gift_none"},
			},
		],
	},
	{
		"id": "kasim_gift_thanks",
		"speaker": "카심",
		"text": "...나한테요? 후드 속에서도 표정이 티 나나 보군. 고맙게 받지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kasim_gift_none",
		"speaker": "카심",
		"narration": "(막상 건넬 것이 없다)",
		"text": "줄 게 없네요.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kasim_wares",
		"speaker": "카심",
		"text": "이래 봬도 꽤 쓸만한 물건들을 갖췄지. 나무, 뼈, 금 등급까지 있네.",
		"affinity_change_on_show": {"npc_id": "kasim", "amount": 2, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[물건을 산다]", "open_weapon_shop": true},
			{"label": "[됐어요]", "next_id": ""},
		],
	},
	{
		"id": "kasim_intro_1",
		"speaker": "카심",
		"text": "카심이라고 하네. 이곳저곳 떠돌면서 장사를 하고 있지, 뭐 대단한 사연은 아니야.",
		"is_decisive": false,
		"options": [
			{"label": "[당신은 몬스터가 아닌가요?]", "next_id": "kasim_intro_2"},
			{"label": "[알겠어요]", "next_id": ""},
		],
	},
	{
		"id": "kasim_intro_2",
		"speaker": "카심",
		"text": "...하하. 눈썰미가 좋군. 뭐, 후드를 쓰고 다니는 데는 다 이유가 있는 법이지.",
		"affinity_change_on_show": {"npc_id": "kasim", "amount": 2, "once": true},
		"is_decisive": false,
		"next_id": "kasim_intro_3",
	},
	{
		"id": "kasim_intro_3",
		"speaker": "카심",
		"text": "그 이상은... 묻지 말아주게. 언젠가 때가 되면, 말할지도 모르지.",
		"is_decisive": false,
		"options": [],
	},
	{
		"id": "kasim_smalltalk_1",
		"speaker": "카심",
		"text": "그럭저럭. 이런 외진 마을까지 찾아오는 손님이 있을 줄은 몰랐지만.",
		"affinity_change_on_show": {"npc_id": "kasim", "amount": 1, "once": true},
		"is_decisive": false,
		"options": [
			{"label": "[작은 마을이라 심심하지 않아요?]", "next_id": "kasim_smalltalk_2"},
			{"label": "[그렇군요]", "next_id": ""},
		],
	},
	{
		"id": "kasim_smalltalk_2",
		"speaker": "카심",
		"text": "심심함이야... 오래 살다 보면 익숙해지지. 아, 이건 그냥 해본 말이야.",
		"affinity_change_on_show": {"npc_id": "kasim", "amount": 1, "once": true},
		"is_decisive": false,
		"options": [],
	},
]

# 동굴 수호자 조우 대화 트리
const GUARDIAN_DIALOGUE: Array = [
	{
		"id": "guardian_entrance",
		"speaker": "",
		"text": "",
		"narration": "(낡은 돌 제단이 입구에 놓여 있다. 오래전에 시든 꽃과 색이 바랜 그릇 몇 개가 그 위에 남아있다. 안쪽에서 희미하지만 분명한 파란빛이 새어나온다)",
		"is_decisive": false,
		"options": [
			{"label": "[들어간다]", "next_id": "guardian_intro_1"},
		],
	},
	{
		"id": "guardian_intro_1",
		"speaker": "???",
		"text": "",
		"narration": "(벽에 새겨진 낡은 문양들이 파란빛을 받아 어렴풋이 드러난다. 물이 흐르던 흔적이 바닥 곳곳에 말라붙어 있다. 그 안쪽에서, 거대한 형체가 몸을 웅크린 채 낮게 신음하고 있다) (형체가 인기척을 느끼고 천천히 고개를 든다. 눈부신 빛과 함께 낮고 긴 울음 같은 소리가 동굴 전체를 울린다)",
		"is_decisive": false,
		"next_id": "guardian_intro_2",
	},
	{
		"id": "guardian_intro_2",
		"speaker": "???",
		"text": "...누구냐. ...또 나를... 없애러 왔나.",
		"is_decisive": false,
		"next_id": "guardian_intro_3",
	},
	{
		"id": "guardian_intro_3",
		"speaker": "???",
		"text": "물길은... 내가 막은 게 아니다. 나는... 지키던 것뿐인데... 무언가 잘못됐어. 나조차... 왜 이렇게 됐는지 모르겠다.",
		"is_decisive": false,
		"next_id": "guardian_decisive",
		"options": [
			{"label": "[이 소리... 미아가 말했던 거랑 같아. 무섭다기보단, 아파하는 것 같은데.]", "next_id": "guardian_decisive", "show_if_flag": "earned_mia_trust"},
		],
	},
	{
		"id": "guardian_decisive",
		"speaker": "???",
		"text": "",
		"narration": "(수호자가 몸을 낮춘다. 싸울 준비를 하는 것처럼도, 체념한 것처럼도 보인다)",
		"is_decisive": true,
		"options": [
			{"label": "[무기를 든다 (전투)]", "next_id": "guardian_fight_result", "flag_to_set": "resolved_guardian_peacefully", "flag_value": false},
			{"label": "[다가가서 말을 건다 (대화 시도)]", "next_id": "guardian_peace_1", "flag_to_set": "resolved_guardian_peacefully", "flag_value": true},
		],
	},
	{
		"id": "guardian_fight_result",
		"speaker": "???",
		"text": "...끝났, 군... ...미안, 하다...",
		"narration": "(형체가 크게 휘청이며 무너진다. 빛이 급격히 잦아든다)",
		"is_decisive": false,
		"next_id": "guardian_fight_aftermath",
	},
	{
		"id": "guardian_fight_aftermath",
		"speaker": "???",
		"text": "",
		"narration": "(완전히 무너져 내리며 빛의 잔재가 흩어진다. 그 순간, 벽 틈 사이사이에서 물이 터져 나오기 시작한다. 처음엔 졸졸 흐르던 물이 순식간에 굵은 물줄기로 바뀌어 동굴 바닥을 가득 채운다. 맑고, 옅은 푸른빛이 감도는 물이다)",
		"is_decisive": false,
		"next_id": "guardian_mono_fight_1",
	},
	{
		"id": "guardian_peace_1",
		"speaker": "???",
		"text": "",
		"narration": "(형체가 위협하듯 몸을 일으키다가, 갑자기 부자연스럽게 움찔거리며 다시 웅크린다. 마치 자기 자신과 싸우고 있는 것처럼)",
		"is_decisive": false,
		"options": [
			{"label": "[잠깐! ...싸우러 온 거 아니야.]", "next_id": "guardian_peace_2"},
		],
	},
	{
		"id": "guardian_peace_2",
		"speaker": "???",
		"text": "",
		"narration": "(형체가 멈칫한다. 낮게 으르렁대지만, 더 다가오지는 않는다)",
		"is_decisive": false,
		"options": [
			{"label": "[너... 지금 뭐랑 싸우고 있는 것 같은데. 뭔데 그래.]", "next_id": "guardian_peace_2b"},
		],
	},
	{
		"id": "guardian_peace_2b",
		"speaker": "???",
		"text": "...하지... 마... 라고... 했는데...",
		"narration": "(형체가 격하게 몸을 떨더니, 알아들을 수 없는 소리를 낮게 흘린다. 신음 사이사이로, 언뜻 사람의 말 같은 것이 섞여 나온다)",
		"is_decisive": false,
		"options": [
			{"label": "[명령... 받고 있는 거야? 그것 때문에 이러는 거야?]", "next_id": "guardian_peace_2c"},
		],
	},
	{
		"id": "guardian_peace_2c",
		"speaker": "???",
		"text": "...그래... 어기면... 아파... 근데... 못 해... 이번엔... 못 해...",
		"narration": "(형체가 순간 그대로 얼어붙는다. 마치 처음으로 자기 말을 알아들은 사람을 만난 것처럼)",
		"is_decisive": false,
		"options": [
			{"label": "[그래서 아팠던 거구나. 그동안 계속.]", "next_id": "guardian_peace_2d"},
		],
	},
	{
		"id": "guardian_peace_2d",
		"speaker": "???",
		"text": "",
		"narration": "(신음이 잠시 잦아들었다가, 다시 격하게 몸부림친다 — 명령과 저항 사이에서 갈등하듯)",
		"is_decisive": false,
		"options": [
			{"label": "[괜찮아. 이제 그만 쉬어도 돼. 그 명령, 안 들어도 돼.]", "next_id": "guardian_peace_calm"},
		],
	},
	{
		"id": "guardian_peace_calm",
		"speaker": "???",
		"text": "...얼마나... 였을까. 이곳에 묶인 지...",
		"narration": "(몸부림이 조금씩 잦아든다. 하지만 완전히 놓지는 못한 채, 거대했던 형체가 흔들리며 서서히 사람에 가까운 윤곽으로 작아진다)",
		"is_decisive": false,
		"next_id": "guardian_peace_gaze",
	},
	{
		"id": "guardian_peace_gaze",
		"speaker": "???",
		"text": "...당신에게서, 뭔가가... 느껴지는군. ...그래, 이 정도면... 됐어. 뒤는... 맡겨도 되겠지.",
		"narration": "(형체가 고개를 들어, 오랫동안 플레이어를 가만히 바라본다. 마치 무언가를 가늠하는 듯한 눈빛)",
		"is_decisive": false,
		"next_id": "guardian_peace_3",
	},
	{
		"id": "guardian_peace_3",
		"speaker": "???",
		"text": "고마워... 정말... 고마워...",
		"narration": "(그 순간, 윤곽이 빛의 입자로 흩어지기 시작한다. 쉬는 게 아니다. 사라지고 있는 것이다)",
		"is_decisive": false,
		"next_id": "guardian_peace_farewell",
	},
	{
		"id": "guardian_peace_farewell",
		"speaker": "???",
		"text": "...감시자들은... 지하에... 있어... 그들이... 전부...",
		"narration": "(말이 채 끝나기도 전에, 마지막 빛의 입자마저 완전히 흩어진다. 그 자리엔 아무것도 남지 않는다. 그리고 그 순간, 벽 틈 사이사이에서 물이 터져 나오기 시작한다. 처음엔 졸졸 흐르던 물이 순식간에 굵은 물줄기로 바뀌어 동굴 바닥을 가득 채운다. 맑고, 옅은 푸른빛이 감도는 물이다)",
		"set_flag_on_show": "guardian_dying_hint_heard",
		"is_decisive": false,
		"next_id": "guardian_mono_peace_1",
	},
	{
		"id": "guardian_mono_fight_1",
		"speaker": "",
		"narration": "(동굴 밖, 해질녘 — 플레이어가 동굴을 나선다. 등 뒤로 물 흐르는 소리가 희미하게 들린다)",
		"text": "...미안하다, 라고 했어. 쓰러지면서, 마지막에.",
		"is_decisive": false,
		"next_id": "guardian_mono_fight_2",
	},
	{
		"id": "guardian_mono_fight_2",
		"speaker": "",
		"text": "괴물이... 그런 말을 할 리가 없잖아. 아니, 애초에 저게 정말 괴물이긴 했던 걸까.",
		"is_decisive": false,
		"next_id": "guardian_mono_fight_3",
	},
	{
		"id": "guardian_mono_fight_3",
		"speaker": "",
		"text": "뭔가 잘못 알고 있었던 건 아닐까, 나.",
		"is_decisive": false,
		"next_id": "guardian_mono_water_1",
	},
	{
		"id": "guardian_mono_peace_1",
		"speaker": "",
		"narration": "(동굴 밖, 해질녘 — 플레이어가 동굴을 나선다. 등 뒤로 물 흐르는 소리가 희미하게 들린다)",
		"text": "...고맙다, 라고 했지. 그리고 물었어, 얼마나 됐냐고. 묶인 지.",
		"is_decisive": false,
		"next_id": "guardian_mono_peace_2",
	},
	{
		"id": "guardian_mono_peace_2",
		"speaker": "",
		"text": "묶여 있었다고...? 그럼 저건 원래 저기 있던 게 아니라, 누군가 가둬놓은 거였다는 건가.",
		"is_decisive": false,
		"next_id": "guardian_mono_peace_3",
	},
	{
		"id": "guardian_mono_peace_3",
		"speaker": "",
		"text": "목소리도, 사라지기 직전 그 모습도... 사람이었어. 분명히.",
		"is_decisive": false,
		"next_id": "guardian_mono_peace_4",
	},
	{
		"id": "guardian_mono_peace_4",
		"speaker": "",
		"text": "사람이 대체 왜 저기 갇혀서, 무슨 일을 겪은 거지.",
		"is_decisive": false,
		"next_id": "guardian_mono_peace_5",
	},
	{
		"id": "guardian_mono_peace_5",
		"speaker": "",
		"text": "...그리고 마지막에 그랬지. \"감시자들은 지하에 있다\"고. 말을 채 끝맺지도 못하고.",
		"is_decisive": false,
		"next_id": "guardian_mono_peace_6",
	},
	{
		"id": "guardian_mono_peace_6",
		"speaker": "",
		"text": "감시자. 지하. 대체 그게 뭔데 — 이 사람을 여기 가둬놓고, 이런 짓까지 할 수 있었던 거지.",
		"is_decisive": false,
		"next_id": "guardian_mono_water_1",
	},
	{
		"id": "guardian_mono_water_1",
		"speaker": "",
		"narration": "(발밑까지 차오른 물을 내려다본다. 동굴 안이 순식간에 얕은 물바다가 되어 있다)",
		"text": "...우물 하나가 마른 거였잖아. 근데 이건, 이 정도 양이 아니잖아.",
		"is_decisive": false,
		"next_id": "guardian_mono_water_2",
	},
	{
		"id": "guardian_mono_water_2",
		"speaker": "",
		"text": "맥이라고 했나. 이렇게나 많이 나올 수 있는 거였어? 지금까지 마을에서 보던 물이랑은 아예 다른데.",
		"is_decisive": false,
		"next_id": "guardian_mono_water_3",
	},
	{
		"id": "guardian_mono_water_3",
		"speaker": "",
		"text": "그럼 우리가 여태 쓰던 물은... 대체 뭐였던 거지.",
		"is_decisive": false,
		"next_id": "guardian_mono_water_4",
	},
	{
		"id": "guardian_mono_water_4",
		"speaker": "",
		"text": "엘라라 촌장님한테 가서 얘기해야겠어. 뭐라고 설명해야 할지는 모르겠지만.",
		"is_decisive": false,
		"options": [],
	},
]

# 게임 최초 시작 시 한 번만 보여주는 오프닝 인트로 (GameState.seen_opening으로 반복 방지).
# 이미지 슬라이드쇼 방식 — 각 노드의 "image"는 배경을 바꿀 때만 적어둔다. 없으면 CutsceneBox가
# 직전 이미지를 그대로 유지(같은 배경에서 텍스트만 두 문단 이어지는 구간용)
const OPENING_IMAGE_VALLEY := "res://assets/graphics/cutscenes/opening_valley.png"
const OPENING_IMAGE_RUINS := "res://assets/graphics/cutscenes/opening_ruins.png"
const OPENING_IMAGE_VILLAGE := "res://assets/graphics/cutscenes/opening_village.png"

const OPENING_DIALOGUE: Array = [
	{
		"id": "opening_1",
		"speaker": "",
		"image": OPENING_IMAGE_VALLEY,
		"narration": "먼 옛날, 대지의 가장 깊은 곳에는 보이지 않는 고대의 물줄기가 흘렀다.",
		"is_decisive": false,
		"next_id": "opening_2",
	},
	{
		"id": "opening_2",
		"speaker": "",
		"narration": "사람들은 그것을 맥이라 불렀고, 숲과 들판, 그리고 인간은 그 푸른 흐름에 기대어 숨을 쉬었다.",
		"is_decisive": false,
		"next_id": "opening_3",
	},
	{
		"id": "opening_3",
		"speaker": "",
		"image": OPENING_IMAGE_RUINS,
		"narration": "영원할 것만 같던 맥이 멈추기 시작한 것은 언제부터였을까. 맥이 마른 자리는 역병이 퍼졌고, 땅은 메마른 비명을 질렀다.",
		"is_decisive": false,
		"next_id": "opening_4",
	},
	{
		"id": "opening_4",
		"speaker": "",
		"image": OPENING_IMAGE_VILLAGE,
		"narration": "이 이야기는 몰락의 소문조차 닿지 않던 변두리의 고요한 마을, '오르시아'의 마지막 맥마저 말라붙으며 시작되는—",
		"is_decisive": false,
		"next_id": "opening_5",
	},
	{
		"id": "opening_5",
		"speaker": "",
		"narration": "한 소년의 이야기, 그 첫 페이지다.",
		"is_decisive": false,
		"options": [],
	},
]
